{
    "expand": "operations,versionedRepresentations,editmeta,changelog,renderedFields",
    "fields": {
        "aggregateprogress": {
            "progress": 0,
            "total": 0
        },
        "aggregatetimeestimate": null,
        "aggregatetimeoriginalestimate": null,
        "aggregatetimespent": null,
        "assignee": null,
        "components": [{
            "id": "12312928",
            "name": "hdfs-client",
            "self": "https://issues.apache.org/jira/rest/api/2/component/12312928"
        }],
        "created": "2011-11-11T20:38:19.000+0000",
        "creator": {
            "active": true,
            "avatarUrls": {
                "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452",
                "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
            },
            "displayName": "Jason Crickmer",
            "key": "jcrickmer",
            "name": "jcrickmer",
            "self": "https://issues.apache.org/jira/rest/api/2/user?username=jcrickmer",
            "timeZone": "Etc/UTC"
        },
        "customfield_10010": null,
        "customfield_12310191": null,
        "customfield_12310192": null,
        "customfield_12310220": "2011-11-11T21:50:46.141+0000",
        "customfield_12310222": "1_*:*_1_*:*_4347012_*|*_5_*:*_1_*:*_0",
        "customfield_12310230": null,
        "customfield_12310250": null,
        "customfield_12310290": null,
        "customfield_12310291": null,
        "customfield_12310300": null,
        "customfield_12310310": "0.0",
        "customfield_12310320": null,
        "customfield_12310420": "216913",
        "customfield_12310920": "113924",
        "customfield_12310921": null,
        "customfield_12311020": null,
        "customfield_12311024": null,
        "customfield_12311120": null,
        "customfield_12311820": "0|i0jutr:",
        "customfield_12312022": null,
        "customfield_12312023": null,
        "customfield_12312024": null,
        "customfield_12312026": null,
        "customfield_12312220": null,
        "customfield_12312320": null,
        "customfield_12312321": null,
        "customfield_12312322": null,
        "customfield_12312323": null,
        "customfield_12312324": null,
        "customfield_12312325": null,
        "customfield_12312326": null,
        "customfield_12312327": null,
        "customfield_12312328": null,
        "customfield_12312329": null,
        "customfield_12312330": null,
        "customfield_12312331": null,
        "customfield_12312332": null,
        "customfield_12312333": null,
        "customfield_12312334": null,
        "customfield_12312335": null,
        "customfield_12312336": null,
        "customfield_12312337": null,
        "customfield_12312338": null,
        "customfield_12312339": null,
        "customfield_12312340": null,
        "customfield_12312341": null,
        "customfield_12312520": null,
        "customfield_12312521": "Fri Nov 11 21:50:46 UTC 2011",
        "customfield_12312720": null,
        "customfield_12312823": null,
        "customfield_12312920": null,
        "customfield_12312921": null,
        "customfield_12312923": null,
        "customfield_12313422": "false",
        "customfield_12313520": null,
        "description": "For the past few weeks I have randomly been receiving errors via the Perl binding of ThriftFS TSocket cannot read 4 bytes.  I thought that it was a symptom of too many clients against the server (say 16 doing a mix of file read and write, as well as listStatus), but in the past couple of days, I have started getting them all the time, even with only 1 client trying to read.  The Perl client error is:\n\n{noformat}\n$VAR1 = bless( {\n                 'code' => 0,\n                 'message' => 'TSocket: timed out reading 4 bytes from bigwws001:9090'\n               }, 'Thrift::TException' );\n{noformat}\n\nThis typically happens in conjunction with errors in other clients, thus initially leading me to believe that it was really a timeout issue.  But after it started occurring with only 1 client running and well within the 10 sec timeout I had set on the TSocket within my Perl client, I checked on the exceptions in the ThriftFS server log:\n\n{noformat}\njava.lang.StringIndexOutOfBoundsException: String index out of range: -1\n        at java.lang.String.checkBounds(String.java:397)\n        at java.lang.String.<init>(String.java:442)\n        at org.apache.hadoop.thriftfs.HadoopThriftServer$HadoopThriftHandler.read(HadoopThriftServer.java:307)\n        at org.apache.hadoop.thriftfs.api.ThriftHadoopFileSystem$Processor$read.process(Unknown Source)\n        at org.apache.hadoop.thriftfs.api.ThriftHadoopFileSystem$Processor.process(Unknown Source)\n        at com.facebook.thrift.server.TThreadPoolServer$WorkerProcess.run(Unknown Source)\n        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)\n        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)\n        at java.lang.Thread.run(Thread.java:662)\n{noformat}\n\n\nThis change seems to have \"solved\" the problem, but this is very much a hack since I do not know the code (maybe throwing an IOException is the right thing to do, and then let it turn into a ThriftIOException?).\n\n{noformat}\n--- src/contrib/thriftfs/src/java/org/apache/hadoop/thriftfs/HadoopThriftServer.java-orig       2011-11-11 09:18:44.000000000 -0600\n+++ src/contrib/thriftfs/src/java/org/apache/hadoop/thriftfs/HadoopThriftServer.java    2011-11-11 09:00:47.000000000 -0600\n@@ -303,8 +303,9 @@\n         }\n         byte[] tmp = new byte[length];\n         int numbytes = in.read(offset, tmp, 0, length);\n-        HadoopThriftHandler.LOG.debug(\"read done: \" + tout.id);\n-        return new String(tmp, 0, numbytes, \"UTF-8\");\n+        HadoopThriftHandler.LOG.debug(\"read done: \" + tout.id +\n+                                     \" numbytes: \" + numbytes);\n+        return new String(tmp, 0, numbytes > 0 ? numbytes : 0, \"UTF-8\");\n       } catch (IOException e) {\n         throw new ThriftIOException(e.getMessage());\n       }\n\n{noformat}\n",
        "duedate": null,
        "environment": "Cloudera Hadoop 0.20.2 distribution running on CentOS 5.5 x64, Java SE 1.6.0_23-b05, Perl 5.14.0",
        "fixVersions": [],
        "issuelinks": [],
        "issuetype": {
            "avatarId": 21133,
            "description": "A problem which impairs or prevents the functions of the product.",
            "iconUrl": "https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype",
            "id": "1",
            "name": "Bug",
            "self": "https://issues.apache.org/jira/rest/api/2/issuetype/1",
            "subtask": false
        },
        "labels": [],
        "lastViewed": null,
        "priority": {
            "iconUrl": "https://issues.apache.org/jira/images/icons/priorities/major.svg",
            "id": "3",
            "name": "Major",
            "self": "https://issues.apache.org/jira/rest/api/2/priority/3"
        },
        "progress": {
            "progress": 0,
            "total": 0
        },
        "project": {
            "avatarUrls": {
                "16x16": "https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=12310942&avatarId=10094",
                "24x24": "https://issues.apache.org/jira/secure/projectavatar?size=small&pid=12310942&avatarId=10094",
                "32x32": "https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=12310942&avatarId=10094",
                "48x48": "https://issues.apache.org/jira/secure/projectavatar?pid=12310942&avatarId=10094"
            },
            "id": "12310942",
            "key": "HDFS",
            "name": "Hadoop HDFS",
            "projectCategory": {
                "description": "Scalable Distributed Computing",
                "id": "10292",
                "name": "Hadoop",
                "self": "https://issues.apache.org/jira/rest/api/2/projectCategory/10292"
            },
            "self": "https://issues.apache.org/jira/rest/api/2/project/12310942"
        },
        "reporter": {
            "active": true,
            "avatarUrls": {
                "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452",
                "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
            },
            "displayName": "Jason Crickmer",
            "key": "jcrickmer",
            "name": "jcrickmer",
            "self": "https://issues.apache.org/jira/rest/api/2/user?username=jcrickmer",
            "timeZone": "Etc/UTC"
        },
        "resolution": {
            "description": "The problem isn't valid and it can't be fixed.",
            "id": "6",
            "name": "Invalid",
            "self": "https://issues.apache.org/jira/rest/api/2/resolution/6"
        },
        "resolutiondate": "2011-11-11T21:50:46.000+0000",
        "status": {
            "description": "A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.",
            "iconUrl": "https://issues.apache.org/jira/images/icons/statuses/resolved.png",
            "id": "5",
            "name": "Resolved",
            "self": "https://issues.apache.org/jira/rest/api/2/status/5",
            "statusCategory": {
                "colorName": "green",
                "id": 3,
                "key": "done",
                "name": "Done",
                "self": "https://issues.apache.org/jira/rest/api/2/statuscategory/3"
            }
        },
        "subtasks": [],
        "summary": "TSocket timed out reading 4 bytes error against HadoopThriftServer from Hadoop-0.20.2 in Perl",
        "timeestimate": null,
        "timeoriginalestimate": null,
        "timespent": null,
        "updated": "2011-11-11T21:50:46.000+0000",
        "versions": [{
            "archived": false,
            "description": "",
            "id": "12314204",
            "name": "0.20.2",
            "releaseDate": "2010-02-16",
            "released": true,
            "self": "https://issues.apache.org/jira/rest/api/2/version/12314204"
        }],
        "votes": {
            "hasVoted": false,
            "self": "https://issues.apache.org/jira/rest/api/2/issue/HDFS-2550/votes",
            "votes": 0
        },
        "watches": {
            "isWatching": false,
            "self": "https://issues.apache.org/jira/rest/api/2/issue/HDFS-2550/watchers",
            "watchCount": 0
        },
        "workratio": -1
    },
    "id": "12531176",
    "key": "HDFS-2550",
    "self": "https://issues.apache.org/jira/rest/api/2/issue/12531176"
}