{
    "expand": "operations,versionedRepresentations,editmeta,changelog,renderedFields",
    "fields": {
        "aggregateprogress": {
            "progress": 0,
            "total": 0
        },
        "aggregatetimeestimate": null,
        "aggregatetimeoriginalestimate": null,
        "aggregatetimespent": null,
        "assignee": null,
        "components": [],
        "created": "2016-10-09T10:55:57.000+0000",
        "creator": {
            "active": true,
            "avatarUrls": {
                "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452",
                "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
            },
            "displayName": "zhouyingchao",
            "key": "sinago",
            "name": "sinago",
            "self": "https://issues.apache.org/jira/rest/api/2/user?username=sinago",
            "timeZone": "Etc/UTC"
        },
        "customfield_10010": null,
        "customfield_12310191": null,
        "customfield_12310192": null,
        "customfield_12310220": null,
        "customfield_12310222": null,
        "customfield_12310230": null,
        "customfield_12310250": null,
        "customfield_12310290": null,
        "customfield_12310291": null,
        "customfield_12310300": null,
        "customfield_12310310": "0.0",
        "customfield_12310320": null,
        "customfield_12310420": "9223372036854775807",
        "customfield_12310920": "9223372036854775807",
        "customfield_12310921": null,
        "customfield_12311020": null,
        "customfield_12311024": null,
        "customfield_12311120": null,
        "customfield_12311820": "0|i34mv3:",
        "customfield_12312022": null,
        "customfield_12312023": null,
        "customfield_12312024": null,
        "customfield_12312026": null,
        "customfield_12312220": null,
        "customfield_12312320": null,
        "customfield_12312321": null,
        "customfield_12312322": null,
        "customfield_12312323": null,
        "customfield_12312324": null,
        "customfield_12312325": null,
        "customfield_12312326": null,
        "customfield_12312327": null,
        "customfield_12312328": null,
        "customfield_12312329": null,
        "customfield_12312330": null,
        "customfield_12312331": null,
        "customfield_12312332": null,
        "customfield_12312333": null,
        "customfield_12312334": null,
        "customfield_12312335": null,
        "customfield_12312336": null,
        "customfield_12312337": null,
        "customfield_12312338": null,
        "customfield_12312339": null,
        "customfield_12312340": null,
        "customfield_12312341": null,
        "customfield_12312520": null,
        "customfield_12312521": "2016-10-09 10:55:57.0",
        "customfield_12312720": null,
        "customfield_12312823": null,
        "customfield_12312920": null,
        "customfield_12312921": null,
        "customfield_12312923": null,
        "customfield_12313422": "false",
        "customfield_12313520": null,
        "description": "On a 2.4 cluster, access to a file failed since the last block length cannot be gotten.  The fsck output of the file at the moment of failure was like this:\n/user/XXXXXXXXX 483600487 bytes, 2 block(s), OPENFORWRITE:  MISSING 1 blocks of total size 215165031 B\n0. BP-219149063-10.108.84.25-1446859315800:blk_2102504098_1035525341 len=268435456 repl=3 [10.112.17.43:11402, 10.118.22.46:11402, 10.118.22.49:11402]\n1. BP-219149063-10.108.84.25-1446859315800:blk_2103114087_1036219054{blockUCState=UNDER_RECOVERY, primaryNodeIndex=2, replicas=[ReplicaUnderConstruction[[DISK]DS-60be75ad-e4a7-4b1e-b3aa-327c85331d42:NORMAL|RBW], ReplicaUnderConstruction[[DISK]DS-184a1ce9-655a-4e67-b0cc-29ab9984bd0a:NORMAL|RBW], ReplicaUnderConstruction[[DISK]DS-6d037ac8-4bcc-4cdc-a803-55b1817e0200:NORMAL|RBW]]} len=215165031 MISSING!  Recorded locations [10.114.10.14:11402, 10.118.29.3:11402, 10.118.22.42:11402]\n\nFrom those three data nodes, we found that there were IOException related to the block and there were pipeline recreating events.\n\nWe figured out that there was a namenode failover event before the issue happened, and there were some updatePipeline calls to the earlier active namenode:\n2016-09-27,15:04:36,437 INFO org.apache.hadoop.hdfs.server.namenode.FSNamesystem: updatePipeline(block=BP-219149063-10.108.84.25-1446859315800:blk_2103114087_1036137092, newGenerationStamp=1036170430, newLength=2624000, newNodes=[10.118.22.42:11402, 10.118.22.49:11402, 10.118.24.3:11402], clientName=DFSClient_NONMAPREDUCE_-442153643_1)\n2016-09-27,15:04:36,438 INFO org.apache.hadoop.hdfs.server.namenode.FSNamesystem: updatePipeline(BP-219149063-10.108.84.25-1446859315800:blk_2103114087_1036137092) successfully to BP-219149063-10.108.84.25-1446859315800:blk_2103114087_1036170430\n2016-09-27,15:10:10,596 INFO org.apache.hadoop.hdfs.server.namenode.FSNamesystem: updatePipeline(block=BP-219149063-10.108.84.25-1446859315800:blk_2103114087_1036170430, newGenerationStamp=1036219054, newLength=17138265, newNodes=[10.118.22.49:11402, 10.118.24.3:11402, 10.114.6.45:11402], clientName=DFSClient_NONMAPREDUCE_-442153643_1)\n2016-09-27,15:10:10,601 INFO org.apache.hadoop.hdfs.server.namenode.FSNamesystem: updatePipeline(BP-219149063-10.108.84.25-1446859315800:blk_2103114087_1036170430) successfully to BP-219149063-10.108.84.25-1446859315800:blk_2103114087_1036219054\n\nWhereas these new data nodes did not show up in the fsck output. It looks like that when data node recovers pipeline (PIPELINE_SETUP_STREAMING_RECOVERY ), the new data nodes would not call notifyNamingnodeReceivingBlock for the transfered block. \n\nFrom code review, the issue also exists in more recent branch.",
        "duedate": null,
        "environment": null,
        "fixVersions": [],
        "issuelinks": [],
        "issuetype": {
            "avatarId": 21133,
            "description": "A problem which impairs or prevents the functions of the product.",
            "iconUrl": "https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype",
            "id": "1",
            "name": "Bug",
            "self": "https://issues.apache.org/jira/rest/api/2/issuetype/1",
            "subtask": false
        },
        "labels": [],
        "lastViewed": null,
        "priority": {
            "iconUrl": "https://issues.apache.org/jira/images/icons/priorities/major.svg",
            "id": "3",
            "name": "Major",
            "self": "https://issues.apache.org/jira/rest/api/2/priority/3"
        },
        "progress": {
            "progress": 0,
            "total": 0
        },
        "project": {
            "avatarUrls": {
                "16x16": "https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=12310942&avatarId=10094",
                "24x24": "https://issues.apache.org/jira/secure/projectavatar?size=small&pid=12310942&avatarId=10094",
                "32x32": "https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=12310942&avatarId=10094",
                "48x48": "https://issues.apache.org/jira/secure/projectavatar?pid=12310942&avatarId=10094"
            },
            "id": "12310942",
            "key": "HDFS",
            "name": "Hadoop HDFS",
            "projectCategory": {
                "description": "Scalable Distributed Computing",
                "id": "10292",
                "name": "Hadoop",
                "self": "https://issues.apache.org/jira/rest/api/2/projectCategory/10292"
            },
            "self": "https://issues.apache.org/jira/rest/api/2/project/12310942"
        },
        "reporter": {
            "active": true,
            "avatarUrls": {
                "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452",
                "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
            },
            "displayName": "zhouyingchao",
            "key": "sinago",
            "name": "sinago",
            "self": "https://issues.apache.org/jira/rest/api/2/user?username=sinago",
            "timeZone": "Etc/UTC"
        },
        "resolution": null,
        "resolutiondate": null,
        "status": {
            "description": "The issue is open and ready for the assignee to start work on it.",
            "iconUrl": "https://issues.apache.org/jira/images/icons/statuses/open.png",
            "id": "1",
            "name": "Open",
            "self": "https://issues.apache.org/jira/rest/api/2/status/1",
            "statusCategory": {
                "colorName": "blue-gray",
                "id": 2,
                "key": "new",
                "name": "To Do",
                "self": "https://issues.apache.org/jira/rest/api/2/statuscategory/2"
            }
        },
        "subtasks": [],
        "summary": "Cannot get last block length after namenode failover",
        "timeestimate": null,
        "timeoriginalestimate": null,
        "timespent": null,
        "updated": "2016-10-11T22:18:56.000+0000",
        "versions": [{
            "archived": false,
            "description": "2.4.1 bug-fix release",
            "id": "12326696",
            "name": "2.4.1",
            "releaseDate": "2014-06-30",
            "released": true,
            "self": "https://issues.apache.org/jira/rest/api/2/version/12326696"
        }],
        "votes": {
            "hasVoted": false,
            "self": "https://issues.apache.org/jira/rest/api/2/issue/HDFS-10989/votes",
            "votes": 0
        },
        "watches": {
            "isWatching": false,
            "self": "https://issues.apache.org/jira/rest/api/2/issue/HDFS-10989/watchers",
            "watchCount": 4
        },
        "workratio": -1
    },
    "id": "13010819",
    "key": "HDFS-10989",
    "self": "https://issues.apache.org/jira/rest/api/2/issue/13010819"
}