{
    "expand": "operations,versionedRepresentations,editmeta,changelog,renderedFields",
    "fields": {
        "aggregateprogress": {
            "progress": 0,
            "total": 0
        },
        "aggregatetimeestimate": null,
        "aggregatetimeoriginalestimate": null,
        "aggregatetimespent": null,
        "assignee": null,
        "components": [{
            "id": "12312928",
            "name": "hdfs-client",
            "self": "https://issues.apache.org/jira/rest/api/2/component/12312928"
        }],
        "created": "2010-06-17T05:24:47.000+0000",
        "creator": {
            "active": true,
            "avatarUrls": {
                "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=thanhdo&avatarId=22565",
                "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=thanhdo&avatarId=22565",
                "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=thanhdo&avatarId=22565",
                "48x48": "https://issues.apache.org/jira/secure/useravatar?ownerId=thanhdo&avatarId=22565"
            },
            "displayName": "Thanh Do",
            "key": "thanhdo",
            "name": "thanhdo",
            "self": "https://issues.apache.org/jira/rest/api/2/user?username=thanhdo",
            "timeZone": "Etc/UTC"
        },
        "customfield_10010": null,
        "customfield_12310191": null,
        "customfield_12310192": null,
        "customfield_12310220": "2014-07-30T20:26:30.020+0000",
        "customfield_12310222": "1_*:*_1_*:*_129999702247_*|*_5_*:*_1_*:*_0",
        "customfield_12310230": null,
        "customfield_12310250": null,
        "customfield_12310290": null,
        "customfield_12310291": null,
        "customfield_12310300": null,
        "customfield_12310310": "0.0",
        "customfield_12310320": null,
        "customfield_12310420": "15909",
        "customfield_12310920": "113406",
        "customfield_12310921": null,
        "customfield_12311020": null,
        "customfield_12311024": null,
        "customfield_12311120": null,
        "customfield_12311820": "0|i0jrmn:",
        "customfield_12312022": null,
        "customfield_12312023": null,
        "customfield_12312024": null,
        "customfield_12312026": null,
        "customfield_12312220": null,
        "customfield_12312320": null,
        "customfield_12312321": null,
        "customfield_12312322": null,
        "customfield_12312323": null,
        "customfield_12312324": null,
        "customfield_12312325": null,
        "customfield_12312326": null,
        "customfield_12312327": null,
        "customfield_12312328": null,
        "customfield_12312329": null,
        "customfield_12312330": null,
        "customfield_12312331": null,
        "customfield_12312332": null,
        "customfield_12312333": null,
        "customfield_12312334": null,
        "customfield_12312335": null,
        "customfield_12312336": null,
        "customfield_12312337": null,
        "customfield_12312338": null,
        "customfield_12312339": null,
        "customfield_12312340": null,
        "customfield_12312341": null,
        "customfield_12312520": null,
        "customfield_12312521": "Wed Jul 30 20:26:30 UTC 2014",
        "customfield_12312720": null,
        "customfield_12312823": null,
        "customfield_12312920": null,
        "customfield_12312921": null,
        "customfield_12312923": null,
        "customfield_12313422": "false",
        "customfield_12313520": null,
        "description": "- Summary: the recoverBlock is not atomic, leading retrial fails when \nfacing a failure.\n \n- Setup:\n+ # available datanodes = 3\n+ # disks / datanode = 1\n+ # failures = 2\n+ failure type = crash\n+ When/where failure happens = (see below)\n \n- Details:\nSuppose there are 3 datanodes in the pipeline: dn3, dn2, and dn1. Dn1 is primary.\nWhen appending, client first calls dn1.recoverBlock to make all the datanodes in \npipeline agree on the new Generation Stamp (GS1) and the length of the block.\nClient then sends a data packet to dn3. dn3 in turn forwards this packet to down stream\ndns (dn2 and dn1) and starts writing to its own disk, then it crashes AFTER writing to the block\nfile but BEFORE writing to the meta file. Client notices the crash, it calls dn1.recoverBlock().\ndn1.recoverBlock() first creates a syncList (by calling getMetadataInfo at all dn2 and dn1).\nThen dn1 calls NameNode.getNextGS() to get new Generation Stamp (GS2).\nThen it calls dn2.updateBlock(), this returns successfully.\nNow, it starts calling its own updateBlock and crashes after renaming from\nblk_X_GS1.meta to blk_X_GS1.meta_tmpGS2.\nTherefore, dn1.recoverBlock() from the client point of view fails.\nbut the GS for corresponding block has been incremented in the namenode (GS2)\nThe client retries by calling dn2.recoverBlock with old GS (GS1), which does not match with\nthe new GS at the NameNode (GS1) -->exception, leading to append fails.\n \nNow, after all, we have\n- in dn3 (which is crashed)\ntmp/blk_X\ntmp/blk_X_GS1.meta\n- in dn2\ncurrent/blk_X\ncurrent/blk_X_GS2\n- in dn1:\ncurrent/blk_X\ncurrent/blk_X_GS1.meta_tmpGS2\n- in NameNode, the block X has generation stamp GS1 (because dn1 has not called\ncommitSyncronization yet).\n \nTherefore, when crashed datanodes restart, at dn1 the block is invalid because \nthere is no meta file. In dn3, block file and meta file are finalized, however, the \nblock is corrupted because CRC mismatch. In dn2, the GS of the block is GS2,\nwhich is not equal with the generation stamp info of the block maintained in NameNode.\nHence, the block blk_X is inaccessible.\n\nThis bug was found by our Failure Testing Service framework:\nhttp://www.eecs.berkeley.edu/Pubs/TechRpts/2010/EECS-2010-98.html\nFor questions, please email us: Thanh Do (thanhdo@cs.wisc.edu) and \nHaryadi Gunawi (haryadi@eecs.berkeley.edu)",
        "duedate": null,
        "environment": null,
        "fixVersions": [],
        "issuelinks": [{
            "id": "12332650",
            "outwardIssue": {
                "fields": {
                    "issuetype": {
                        "avatarId": 21133,
                        "description": "A problem which impairs or prevents the functions of the product.",
                        "iconUrl": "https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype",
                        "id": "1",
                        "name": "Bug",
                        "self": "https://issues.apache.org/jira/rest/api/2/issuetype/1",
                        "subtask": false
                    },
                    "priority": {
                        "iconUrl": "https://issues.apache.org/jira/images/icons/priorities/critical.svg",
                        "id": "2",
                        "name": "Critical",
                        "self": "https://issues.apache.org/jira/rest/api/2/priority/2"
                    },
                    "status": {
                        "description": "The issue is considered finished, the resolution is correct. Issues which are not closed can be reopened.",
                        "iconUrl": "https://issues.apache.org/jira/images/icons/statuses/closed.png",
                        "id": "6",
                        "name": "Closed",
                        "self": "https://issues.apache.org/jira/rest/api/2/status/6",
                        "statusCategory": {
                            "colorName": "green",
                            "id": 3,
                            "key": "done",
                            "name": "Done",
                            "self": "https://issues.apache.org/jira/rest/api/2/statuscategory/3"
                        }
                    },
                    "summary": "0.20: Block lost when multiple DNs trying to recover it to different genstamps"
                },
                "id": "12467648",
                "key": "HDFS-1260",
                "self": "https://issues.apache.org/jira/rest/api/2/issue/12467648"
            },
            "self": "https://issues.apache.org/jira/rest/api/2/issueLink/12332650",
            "type": {
                "id": "10030",
                "inward": "is related to",
                "name": "Reference",
                "outward": "relates to",
                "self": "https://issues.apache.org/jira/rest/api/2/issueLinkType/10030"
            }
        }],
        "issuetype": {
            "avatarId": 21133,
            "description": "A problem which impairs or prevents the functions of the product.",
            "iconUrl": "https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype",
            "id": "1",
            "name": "Bug",
            "self": "https://issues.apache.org/jira/rest/api/2/issuetype/1",
            "subtask": false
        },
        "labels": [],
        "lastViewed": null,
        "priority": {
            "iconUrl": "https://issues.apache.org/jira/images/icons/priorities/major.svg",
            "id": "3",
            "name": "Major",
            "self": "https://issues.apache.org/jira/rest/api/2/priority/3"
        },
        "progress": {
            "progress": 0,
            "total": 0
        },
        "project": {
            "avatarUrls": {
                "16x16": "https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=12310942&avatarId=10094",
                "24x24": "https://issues.apache.org/jira/secure/projectavatar?size=small&pid=12310942&avatarId=10094",
                "32x32": "https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=12310942&avatarId=10094",
                "48x48": "https://issues.apache.org/jira/secure/projectavatar?pid=12310942&avatarId=10094"
            },
            "id": "12310942",
            "key": "HDFS",
            "name": "Hadoop HDFS",
            "projectCategory": {
                "description": "Scalable Distributed Computing",
                "id": "10292",
                "name": "Hadoop",
                "self": "https://issues.apache.org/jira/rest/api/2/projectCategory/10292"
            },
            "self": "https://issues.apache.org/jira/rest/api/2/project/12310942"
        },
        "reporter": {
            "active": true,
            "avatarUrls": {
                "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=thanhdo&avatarId=22565",
                "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=thanhdo&avatarId=22565",
                "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=thanhdo&avatarId=22565",
                "48x48": "https://issues.apache.org/jira/secure/useravatar?ownerId=thanhdo&avatarId=22565"
            },
            "displayName": "Thanh Do",
            "key": "thanhdo",
            "name": "thanhdo",
            "self": "https://issues.apache.org/jira/rest/api/2/user?username=thanhdo",
            "timeZone": "Etc/UTC"
        },
        "resolution": {
            "description": "The problem described is an issue which will never be fixed.",
            "id": "2",
            "name": "Won't Fix",
            "self": "https://issues.apache.org/jira/rest/api/2/resolution/2"
        },
        "resolutiondate": "2014-07-30T20:26:29.000+0000",
        "status": {
            "description": "A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.",
            "iconUrl": "https://issues.apache.org/jira/images/icons/statuses/resolved.png",
            "id": "5",
            "name": "Resolved",
            "self": "https://issues.apache.org/jira/rest/api/2/status/5",
            "statusCategory": {
                "colorName": "green",
                "id": 3,
                "key": "done",
                "name": "Done",
                "self": "https://issues.apache.org/jira/rest/api/2/statuscategory/3"
            }
        },
        "subtasks": [],
        "summary": "Generation Stamp mismatches, leading to failed append",
        "timeestimate": null,
        "timeoriginalestimate": null,
        "timespent": null,
        "updated": "2014-07-30T20:26:30.000+0000",
        "versions": [{
            "archived": true,
            "description": "Append/sync support for Hadoop 0.20",
            "id": "12315103",
            "name": "0.20-append",
            "released": false,
            "self": "https://issues.apache.org/jira/rest/api/2/version/12315103"
        }],
        "votes": {
            "hasVoted": false,
            "self": "https://issues.apache.org/jira/rest/api/2/issue/HDFS-1231/votes",
            "votes": 0
        },
        "watches": {
            "isWatching": false,
            "self": "https://issues.apache.org/jira/rest/api/2/issue/HDFS-1231/watchers",
            "watchCount": 3
        },
        "workratio": -1
    },
    "id": "12467166",
    "key": "HDFS-1231",
    "self": "https://issues.apache.org/jira/rest/api/2/issue/12467166"
}