{
    "expand": "operations,versionedRepresentations,editmeta,changelog,renderedFields",
    "fields": {
        "aggregateprogress": {
            "progress": 0,
            "total": 0
        },
        "aggregatetimeestimate": null,
        "aggregatetimeoriginalestimate": null,
        "aggregatetimespent": null,
        "assignee": null,
        "components": [{
            "id": "12310740",
            "name": "util",
            "self": "https://issues.apache.org/jira/rest/api/2/component/12310740"
        }],
        "created": "2017-09-07T07:20:23.000+0000",
        "creator": {
            "active": true,
            "avatarUrls": {
                "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452",
                "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
            },
            "displayName": "Yuqi Wang",
            "key": "yqwang",
            "name": "yqwang",
            "self": "https://issues.apache.org/jira/rest/api/2/user?username=yqwang",
            "timeZone": "Etc/UTC"
        },
        "customfield_10010": null,
        "customfield_12310191": null,
        "customfield_12310192": "Initialize shell exit code to EXIT_CODE_NOT_AVAILABLE instead of 0 to avoid hiding failures happen before setting it to the real shell sub process exit code.",
        "customfield_12310220": "2017-09-07T09:31:37.683+0000",
        "customfield_12310222": null,
        "customfield_12310230": null,
        "customfield_12310250": [
            {
                "id": "10430",
                "self": "https://issues.apache.org/jira/rest/api/2/customFieldOption/10430",
                "value": "Patch"
            },
            {
                "id": "10431",
                "self": "https://issues.apache.org/jira/rest/api/2/customFieldOption/10431",
                "value": "Important"
            }
        ],
        "customfield_12310290": null,
        "customfield_12310291": null,
        "customfield_12310300": null,
        "customfield_12310310": "2.0",
        "customfield_12310320": [{
            "archived": false,
            "description": "Hadoop 3.3.0",
            "id": "12343764",
            "name": "3.3.0",
            "released": false,
            "self": "https://issues.apache.org/jira/rest/api/2/version/12343764"
        }],
        "customfield_12310420": "9223372036854775807",
        "customfield_12310920": "9223372036854775807",
        "customfield_12310921": null,
        "customfield_12311020": null,
        "customfield_12311024": null,
        "customfield_12311120": null,
        "customfield_12311820": "0|i3jr0n:",
        "customfield_12312022": null,
        "customfield_12312023": null,
        "customfield_12312024": null,
        "customfield_12312026": null,
        "customfield_12312220": null,
        "customfield_12312320": null,
        "customfield_12312321": null,
        "customfield_12312322": null,
        "customfield_12312323": null,
        "customfield_12312324": null,
        "customfield_12312325": null,
        "customfield_12312326": null,
        "customfield_12312327": null,
        "customfield_12312328": null,
        "customfield_12312329": null,
        "customfield_12312330": null,
        "customfield_12312331": null,
        "customfield_12312332": null,
        "customfield_12312333": null,
        "customfield_12312334": null,
        "customfield_12312335": null,
        "customfield_12312336": null,
        "customfield_12312337": null,
        "customfield_12312338": null,
        "customfield_12312339": null,
        "customfield_12312340": null,
        "customfield_12312341": null,
        "customfield_12312520": null,
        "customfield_12312521": "Fri Nov 23 11:56:04 UTC 2018",
        "customfield_12312720": null,
        "customfield_12312823": null,
        "customfield_12312920": null,
        "customfield_12312921": null,
        "customfield_12312923": null,
        "customfield_12313422": "false",
        "customfield_12313520": null,
        "description": "*Hadoop may hide shell failures (including start container and fs operation failures), such as:*\n\nContainer exit diagnostics (note the container exit code is 0):\n\n{code:java}\nException from container-launch. Container id: container_e5620_1503888150197_2979_01_003320\nExit code: 0\nException message: \n  Cannot run program \"D:\\data\\hadoop.latest\\bin\\winutils.exe\" (in directory \"\\data\\yarnnm\\local\\usercache\\hadoop\\appcache\\application_1503888150197_2979\\container_e5620_1503888150197_2979_01_003320\"): \n  CreateProcess error=2, The system cannot find the file specified\n  Stack trace: java.io.IOException: Cannot run program \"D:\\data\\hadoop.latest\\bin\\winutils.exe\" (in directory \"\\data\\yarnnm\\local\\usercache\\hadoop\\appcache\\application_1503888150197_2979\\container_e5620_1503888150197_2979_01_003320\"): CreateProcess error=2, The system cannot find the file specified\n    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)\n    at org.apache.hadoop.util.Shell.runCommand(Shell.java:517)\n    at org.apache.hadoop.util.Shell.run(Shell.java:490)\n    at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:756)\n    at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:212)\n    at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:329)\n    at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:86)\n    at java.util.concurrent.FutureTask.run(FutureTask.java:266)\n    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n    at java.lang.Thread.run(Thread.java:745)\n{code}\n",
        "duedate": null,
        "environment": null,
        "fixVersions": [{
            "archived": false,
            "id": "12339180",
            "name": "3.0.0-alpha4",
            "releaseDate": "2017-07-07",
            "released": true,
            "self": "https://issues.apache.org/jira/rest/api/2/version/12339180"
        }],
        "issuelinks": [],
        "issuetype": {
            "avatarId": 21133,
            "description": "A problem which impairs or prevents the functions of the product.",
            "iconUrl": "https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype",
            "id": "1",
            "name": "Bug",
            "self": "https://issues.apache.org/jira/rest/api/2/issuetype/1",
            "subtask": false
        },
        "labels": ["shell"],
        "lastViewed": null,
        "priority": {
            "iconUrl": "https://issues.apache.org/jira/images/icons/priorities/major.svg",
            "id": "3",
            "name": "Major",
            "self": "https://issues.apache.org/jira/rest/api/2/priority/3"
        },
        "progress": {
            "progress": 0,
            "total": 0
        },
        "project": {
            "avatarUrls": {
                "16x16": "https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=12310240&avatarId=10095",
                "24x24": "https://issues.apache.org/jira/secure/projectavatar?size=small&pid=12310240&avatarId=10095",
                "32x32": "https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=12310240&avatarId=10095",
                "48x48": "https://issues.apache.org/jira/secure/projectavatar?pid=12310240&avatarId=10095"
            },
            "id": "12310240",
            "key": "HADOOP",
            "name": "Hadoop Common",
            "projectCategory": {
                "description": "Scalable Distributed Computing",
                "id": "10292",
                "name": "Hadoop",
                "self": "https://issues.apache.org/jira/rest/api/2/projectCategory/10292"
            },
            "self": "https://issues.apache.org/jira/rest/api/2/project/12310240"
        },
        "reporter": {
            "active": true,
            "avatarUrls": {
                "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452",
                "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
            },
            "displayName": "Yuqi Wang",
            "key": "yqwang",
            "name": "yqwang",
            "self": "https://issues.apache.org/jira/rest/api/2/user?username=yqwang",
            "timeZone": "Etc/UTC"
        },
        "resolution": null,
        "resolutiondate": null,
        "status": {
            "description": "A patch for this issue has been uploaded to JIRA by a contributor.",
            "iconUrl": "https://issues.apache.org/jira/images/icons/statuses/document.png",
            "id": "10002",
            "name": "Patch Available",
            "self": "https://issues.apache.org/jira/rest/api/2/status/10002",
            "statusCategory": {
                "colorName": "yellow",
                "id": 4,
                "key": "indeterminate",
                "name": "In Progress",
                "self": "https://issues.apache.org/jira/rest/api/2/statuscategory/4"
            }
        },
        "subtasks": [],
        "summary": "Wrong shell exit code if the shell process cannot be even started",
        "timeestimate": null,
        "timeoriginalestimate": null,
        "timespent": null,
        "updated": "2018-11-23T11:56:04.000+0000",
        "versions": [{
            "archived": false,
            "description": "2.7.1 release",
            "id": "12331977",
            "name": "2.7.1",
            "releaseDate": "2015-07-06",
            "released": true,
            "self": "https://issues.apache.org/jira/rest/api/2/version/12331977"
        }],
        "votes": {
            "hasVoted": false,
            "self": "https://issues.apache.org/jira/rest/api/2/issue/HADOOP-14846/votes",
            "votes": 0
        },
        "watches": {
            "isWatching": false,
            "self": "https://issues.apache.org/jira/rest/api/2/issue/HADOOP-14846/watchers",
            "watchCount": 5
        },
        "workratio": -1
    },
    "id": "13100386",
    "key": "HADOOP-14846",
    "self": "https://issues.apache.org/jira/rest/api/2/issue/13100386"
}