{
    "expand": "operations,versionedRepresentations,editmeta,changelog,renderedFields",
    "fields": {
        "aggregateprogress": {
            "progress": 0,
            "total": 0
        },
        "aggregatetimeestimate": null,
        "aggregatetimeoriginalestimate": null,
        "aggregatetimespent": null,
        "assignee": {
            "active": true,
            "avatarUrls": {
                "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452",
                "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
            },
            "displayName": "Yongjun Zhang",
            "key": "yzhangal",
            "name": "yzhangal",
            "self": "https://issues.apache.org/jira/rest/api/2/user?username=yzhangal",
            "timeZone": "America/Los_Angeles"
        },
        "components": [{
            "id": "12312526",
            "name": "security",
            "self": "https://issues.apache.org/jira/rest/api/2/component/12312526"
        }],
        "created": "2015-01-07T21:19:57.000+0000",
        "creator": {
            "active": true,
            "avatarUrls": {
                "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452",
                "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
            },
            "displayName": "Robert Kanter",
            "key": "rkanter",
            "name": "rkanter",
            "self": "https://issues.apache.org/jira/rest/api/2/user?username=rkanter",
            "timeZone": "America/Los_Angeles"
        },
        "customfield_10010": null,
        "customfield_12310191": [{
            "id": "10343",
            "self": "https://issues.apache.org/jira/rest/api/2/customFieldOption/10343",
            "value": "Reviewed"
        }],
        "customfield_12310192": null,
        "customfield_12310220": "2015-01-07T21:30:03.482+0000",
        "customfield_12310222": "10002_*:*_1_*:*_1960828317_*|*_1_*:*_1_*:*_1239532060_*|*_5_*:*_1_*:*_0",
        "customfield_12310230": null,
        "customfield_12310250": null,
        "customfield_12310290": null,
        "customfield_12310291": null,
        "customfield_12310300": null,
        "customfield_12310310": "4.0",
        "customfield_12310320": [{
            "archived": false,
            "description": "2.7.0 release",
            "id": "12327583",
            "name": "2.7.0",
            "releaseDate": "2015-04-20",
            "released": true,
            "self": "https://issues.apache.org/jira/rest/api/2/version/12327583"
        }],
        "customfield_12310420": "9223372036854775807",
        "customfield_12310920": "9223372036854775807",
        "customfield_12310921": null,
        "customfield_12311020": null,
        "customfield_12311024": null,
        "customfield_12311120": null,
        "customfield_12311820": "0|i241s7:",
        "customfield_12312022": null,
        "customfield_12312023": null,
        "customfield_12312024": null,
        "customfield_12312026": null,
        "customfield_12312220": null,
        "customfield_12312320": null,
        "customfield_12312321": null,
        "customfield_12312322": null,
        "customfield_12312323": null,
        "customfield_12312324": null,
        "customfield_12312325": null,
        "customfield_12312326": null,
        "customfield_12312327": null,
        "customfield_12312328": null,
        "customfield_12312329": null,
        "customfield_12312330": null,
        "customfield_12312331": null,
        "customfield_12312332": null,
        "customfield_12312333": null,
        "customfield_12312334": null,
        "customfield_12312335": null,
        "customfield_12312336": null,
        "customfield_12312337": null,
        "customfield_12312338": null,
        "customfield_12312339": null,
        "customfield_12312340": null,
        "customfield_12312341": null,
        "customfield_12312520": null,
        "customfield_12312521": "Tue Feb 17 08:12:46 UTC 2015",
        "customfield_12312720": null,
        "customfield_12312823": null,
        "customfield_12312920": null,
        "customfield_12312921": null,
        "customfield_12312923": null,
        "customfield_12313422": "false",
        "customfield_12313520": null,
        "description": "While looking at HADOOP-10895, we discovered that the {{KerberosAuthenticator}} can authenticate with a non-secure cluster, even without falling back.\n\nThe problematic code is here:\n{code:java}\n      if (conn.getResponseCode() == HttpURLConnection.HTTP_OK) {    // <----- A\n        LOG.debug(\"JDK performed authentication on our behalf.\");\n        // If the JDK already did the SPNEGO back-and-forth for\n        // us, just pull out the token.\n        AuthenticatedURL.extractToken(conn, token);\n        return;\n      } else if (isNegotiate()) {                                   // <----- B\n        LOG.debug(\"Performing our own SPNEGO sequence.\");\n        doSpnegoSequence(token);\n      } else {                                                      // <----- C\n        LOG.debug(\"Using fallback authenticator sequence.\");\n        Authenticator auth = getFallBackAuthenticator();\n        // Make sure that the fall back authenticator have the same\n        // ConnectionConfigurator, since the method might be overridden.\n        // Otherwise the fall back authenticator might not have the information\n        // to make the connection (e.g., SSL certificates)\n        auth.setConnectionConfigurator(connConfigurator);\n        auth.authenticate(url, token);\n      }\n    }\n{code}\nSometimes the JVM does the SPNEGO for us, and path A is used.  However, if the {{KerberosAuthenticator}} tries to talk to a non-secure cluster, path A also succeeds in this case.  \nMore details can be found in this comment:\nhttps://issues.apache.org/jira/browse/HADOOP-10895?focusedCommentId=14247476&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14247476\n\nWe've actually dealt with this before.  HADOOP-8883 tried to fix a related problem by adding another condition to path A that would look for a header.  However, the JVM hides this header, making path A never occur.  We reverted this change in HADOOP-10078, and didn't realize that there was still a problem until now.",
        "duedate": null,
        "environment": null,
        "fixVersions": [{
            "archived": false,
            "description": "2.7.0 release",
            "id": "12327583",
            "name": "2.7.0",
            "releaseDate": "2015-04-20",
            "released": true,
            "self": "https://issues.apache.org/jira/rest/api/2/version/12327583"
        }],
        "issuelinks": [
            {
                "id": "12404782",
                "outwardIssue": {
                    "fields": {
                        "issuetype": {
                            "avatarId": 21133,
                            "description": "A problem which impairs or prevents the functions of the product.",
                            "iconUrl": "https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype",
                            "id": "1",
                            "name": "Bug",
                            "self": "https://issues.apache.org/jira/rest/api/2/issuetype/1",
                            "subtask": false
                        },
                        "priority": {
                            "iconUrl": "https://issues.apache.org/jira/images/icons/priorities/critical.svg",
                            "id": "2",
                            "name": "Critical",
                            "self": "https://issues.apache.org/jira/rest/api/2/priority/2"
                        },
                        "status": {
                            "description": "The issue is open and ready for the assignee to start work on it.",
                            "iconUrl": "https://issues.apache.org/jira/images/icons/statuses/open.png",
                            "id": "1",
                            "name": "Open",
                            "self": "https://issues.apache.org/jira/rest/api/2/status/1",
                            "statusCategory": {
                                "colorName": "blue-gray",
                                "id": 2,
                                "key": "new",
                                "name": "To Do",
                                "self": "https://issues.apache.org/jira/rest/api/2/statuscategory/2"
                            }
                        },
                        "summary": "HTTP KerberosAuthenticator fallback should have a flag to disable it"
                    },
                    "id": "12729529",
                    "key": "HADOOP-10895",
                    "self": "https://issues.apache.org/jira/rest/api/2/issue/12729529"
                },
                "self": "https://issues.apache.org/jira/rest/api/2/issueLink/12404782",
                "type": {
                    "id": "10030",
                    "inward": "is related to",
                    "name": "Reference",
                    "outward": "relates to",
                    "self": "https://issues.apache.org/jira/rest/api/2/issueLinkType/10030"
                }
            },
            {
                "id": "12432294",
                "outwardIssue": {
                    "fields": {
                        "issuetype": {
                            "avatarId": 21133,
                            "description": "A problem which impairs or prevents the functions of the product.",
                            "iconUrl": "https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype",
                            "id": "1",
                            "name": "Bug",
                            "self": "https://issues.apache.org/jira/rest/api/2/issuetype/1",
                            "subtask": false
                        },
                        "priority": {
                            "iconUrl": "https://issues.apache.org/jira/images/icons/priorities/major.svg",
                            "id": "3",
                            "name": "Major",
                            "self": "https://issues.apache.org/jira/rest/api/2/priority/3"
                        },
                        "status": {
                            "description": "The issue is considered finished, the resolution is correct. Issues which are not closed can be reopened.",
                            "iconUrl": "https://issues.apache.org/jira/images/icons/statuses/closed.png",
                            "id": "6",
                            "name": "Closed",
                            "self": "https://issues.apache.org/jira/rest/api/2/status/6",
                            "statusCategory": {
                                "colorName": "green",
                                "id": 3,
                                "key": "done",
                                "name": "Done",
                                "self": "https://issues.apache.org/jira/rest/api/2/statuscategory/3"
                            }
                        },
                        "summary": "TestOozieCLI.testshareLibUpdate_withSecurity fails with Hadoop 2"
                    },
                    "id": "12849049",
                    "key": "OOZIE-2315",
                    "self": "https://issues.apache.org/jira/rest/api/2/issue/12849049"
                },
                "self": "https://issues.apache.org/jira/rest/api/2/issueLink/12432294",
                "type": {
                    "id": "10030",
                    "inward": "is related to",
                    "name": "Reference",
                    "outward": "relates to",
                    "self": "https://issues.apache.org/jira/rest/api/2/issueLinkType/10030"
                }
            },
            {
                "id": "12404781",
                "inwardIssue": {
                    "fields": {
                        "issuetype": {
                            "avatarId": 21133,
                            "description": "A problem which impairs or prevents the functions of the product.",
                            "iconUrl": "https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype",
                            "id": "1",
                            "name": "Bug",
                            "self": "https://issues.apache.org/jira/rest/api/2/issuetype/1",
                            "subtask": false
                        },
                        "priority": {
                            "iconUrl": "https://issues.apache.org/jira/images/icons/priorities/major.svg",
                            "id": "3",
                            "name": "Major",
                            "self": "https://issues.apache.org/jira/rest/api/2/priority/3"
                        },
                        "status": {
                            "description": "The issue is considered finished, the resolution is correct. Issues which are not closed can be reopened.",
                            "iconUrl": "https://issues.apache.org/jira/images/icons/statuses/closed.png",
                            "id": "6",
                            "name": "Closed",
                            "self": "https://issues.apache.org/jira/rest/api/2/status/6",
                            "statusCategory": {
                                "colorName": "green",
                                "id": 3,
                                "key": "done",
                                "name": "Done",
                                "self": "https://issues.apache.org/jira/rest/api/2/statuscategory/3"
                            }
                        },
                        "summary": "Anonymous fallback in KerberosAuthenticator is broken"
                    },
                    "id": "12610375",
                    "key": "HADOOP-8883",
                    "self": "https://issues.apache.org/jira/rest/api/2/issue/12610375"
                },
                "self": "https://issues.apache.org/jira/rest/api/2/issueLink/12404781",
                "type": {
                    "id": "10030",
                    "inward": "is related to",
                    "name": "Reference",
                    "outward": "relates to",
                    "self": "https://issues.apache.org/jira/rest/api/2/issueLinkType/10030"
                }
            },
            {
                "id": "12404780",
                "inwardIssue": {
                    "fields": {
                        "issuetype": {
                            "avatarId": 21133,
                            "description": "A problem which impairs or prevents the functions of the product.",
                            "iconUrl": "https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype",
                            "id": "1",
                            "name": "Bug",
                            "self": "https://issues.apache.org/jira/rest/api/2/issuetype/1",
                            "subtask": false
                        },
                        "priority": {
                            "iconUrl": "https://issues.apache.org/jira/images/icons/priorities/minor.svg",
                            "id": "4",
                            "name": "Minor",
                            "self": "https://issues.apache.org/jira/rest/api/2/priority/4"
                        },
                        "status": {
                            "description": "The issue is considered finished, the resolution is correct. Issues which are not closed can be reopened.",
                            "iconUrl": "https://issues.apache.org/jira/images/icons/statuses/closed.png",
                            "id": "6",
                            "name": "Closed",
                            "self": "https://issues.apache.org/jira/rest/api/2/status/6",
                            "statusCategory": {
                                "colorName": "green",
                                "id": 3,
                                "key": "done",
                                "name": "Done",
                                "self": "https://issues.apache.org/jira/rest/api/2/statuscategory/3"
                            }
                        },
                        "summary": "KerberosAuthenticator always does SPNEGO"
                    },
                    "id": "12676957",
                    "key": "HADOOP-10078",
                    "self": "https://issues.apache.org/jira/rest/api/2/issue/12676957"
                },
                "self": "https://issues.apache.org/jira/rest/api/2/issueLink/12404780",
                "type": {
                    "id": "10030",
                    "inward": "is related to",
                    "name": "Reference",
                    "outward": "relates to",
                    "self": "https://issues.apache.org/jira/rest/api/2/issueLinkType/10030"
                }
            }
        ],
        "issuetype": {
            "avatarId": 21133,
            "description": "A problem which impairs or prevents the functions of the product.",
            "iconUrl": "https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype",
            "id": "1",
            "name": "Bug",
            "self": "https://issues.apache.org/jira/rest/api/2/issuetype/1",
            "subtask": false
        },
        "labels": [],
        "lastViewed": null,
        "priority": {
            "iconUrl": "https://issues.apache.org/jira/images/icons/priorities/critical.svg",
            "id": "2",
            "name": "Critical",
            "self": "https://issues.apache.org/jira/rest/api/2/priority/2"
        },
        "progress": {
            "progress": 0,
            "total": 0
        },
        "project": {
            "avatarUrls": {
                "16x16": "https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=12310240&avatarId=10095",
                "24x24": "https://issues.apache.org/jira/secure/projectavatar?size=small&pid=12310240&avatarId=10095",
                "32x32": "https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=12310240&avatarId=10095",
                "48x48": "https://issues.apache.org/jira/secure/projectavatar?pid=12310240&avatarId=10095"
            },
            "id": "12310240",
            "key": "HADOOP",
            "name": "Hadoop Common",
            "projectCategory": {
                "description": "Scalable Distributed Computing",
                "id": "10292",
                "name": "Hadoop",
                "self": "https://issues.apache.org/jira/rest/api/2/projectCategory/10292"
            },
            "self": "https://issues.apache.org/jira/rest/api/2/project/12310240"
        },
        "reporter": {
            "active": true,
            "avatarUrls": {
                "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452",
                "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452",
                "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452",
                "48x48": "https://issues.apache.org/jira/secure/useravatar?avatarId=10452"
            },
            "displayName": "Robert Kanter",
            "key": "rkanter",
            "name": "rkanter",
            "self": "https://issues.apache.org/jira/rest/api/2/user?username=rkanter",
            "timeZone": "America/Los_Angeles"
        },
        "resolution": {
            "description": "A fix for this issue is checked into the tree and tested.",
            "id": "1",
            "name": "Fixed",
            "self": "https://issues.apache.org/jira/rest/api/2/resolution/1"
        },
        "resolutiondate": "2015-02-13T22:19:17.000+0000",
        "status": {
            "description": "The issue is considered finished, the resolution is correct. Issues which are not closed can be reopened.",
            "iconUrl": "https://issues.apache.org/jira/images/icons/statuses/closed.png",
            "id": "6",
            "name": "Closed",
            "self": "https://issues.apache.org/jira/rest/api/2/status/6",
            "statusCategory": {
                "colorName": "green",
                "id": 3,
                "key": "done",
                "name": "Done",
                "self": "https://issues.apache.org/jira/rest/api/2/statuscategory/3"
            }
        },
        "subtasks": [],
        "summary": "KerberosAuthenticator can connect to a non-secure cluster",
        "timeestimate": null,
        "timeoriginalestimate": null,
        "timespent": null,
        "updated": "2015-07-27T20:19:48.000+0000",
        "versions": [{
            "archived": false,
            "description": "2.6.0 release",
            "id": "12327179",
            "name": "2.6.0",
            "releaseDate": "2014-11-18",
            "released": true,
            "self": "https://issues.apache.org/jira/rest/api/2/version/12327179"
        }],
        "votes": {
            "hasVoted": false,
            "self": "https://issues.apache.org/jira/rest/api/2/issue/HADOOP-11467/votes",
            "votes": 0
        },
        "watches": {
            "isWatching": false,
            "self": "https://issues.apache.org/jira/rest/api/2/issue/HADOOP-11467/watchers",
            "watchCount": 7
        },
        "workratio": -1
    },
    "id": "12765466",
    "key": "HADOOP-11467",
    "self": "https://issues.apache.org/jira/rest/api/2/issue/12765466"
}