{
    "expand": "operations,versionedRepresentations,editmeta,changelog,renderedFields",
    "fields": {
        "aggregateprogress": {
            "progress": 0,
            "total": 0
        },
        "aggregatetimeestimate": null,
        "aggregatetimeoriginalestimate": null,
        "aggregatetimespent": null,
        "assignee": {
            "active": true,
            "avatarUrls": {
                "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=osayankin&avatarId=34533",
                "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=osayankin&avatarId=34533",
                "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=osayankin&avatarId=34533",
                "48x48": "https://issues.apache.org/jira/secure/useravatar?ownerId=osayankin&avatarId=34533"
            },
            "displayName": "Oleksiy Sayankin",
            "key": "osayankin",
            "name": "osayankin",
            "self": "https://issues.apache.org/jira/rest/api/2/user?username=osayankin",
            "timeZone": "Etc/UTC"
        },
        "components": [{
            "description": "Transaction management and ACID",
            "id": "12322671",
            "name": "Transactions",
            "self": "https://issues.apache.org/jira/rest/api/2/component/12322671"
        }],
        "created": "2018-05-17T16:05:05.000+0000",
        "creator": {
            "active": true,
            "avatarUrls": {
                "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=osayankin&avatarId=34533",
                "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=osayankin&avatarId=34533",
                "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=osayankin&avatarId=34533",
                "48x48": "https://issues.apache.org/jira/secure/useravatar?ownerId=osayankin&avatarId=34533"
            },
            "displayName": "Oleksiy Sayankin",
            "key": "osayankin",
            "name": "osayankin",
            "self": "https://issues.apache.org/jira/rest/api/2/user?username=osayankin",
            "timeZone": "Etc/UTC"
        },
        "customfield_10010": null,
        "customfield_12310191": null,
        "customfield_12310192": null,
        "customfield_12310220": "2018-05-25T05:49:29.478+0000",
        "customfield_12310222": null,
        "customfield_12310230": null,
        "customfield_12310250": null,
        "customfield_12310290": null,
        "customfield_12310291": null,
        "customfield_12310300": null,
        "customfield_12310310": "1.0",
        "customfield_12310320": null,
        "customfield_12310420": "9223372036854775807",
        "customfield_12310920": "9223372036854775807",
        "customfield_12310921": null,
        "customfield_12311020": null,
        "customfield_12311024": null,
        "customfield_12311120": null,
        "customfield_12311820": "0|i3tua7:",
        "customfield_12312022": null,
        "customfield_12312023": null,
        "customfield_12312024": null,
        "customfield_12312026": null,
        "customfield_12312220": null,
        "customfield_12312320": null,
        "customfield_12312321": null,
        "customfield_12312322": null,
        "customfield_12312323": null,
        "customfield_12312324": null,
        "customfield_12312325": null,
        "customfield_12312326": null,
        "customfield_12312327": null,
        "customfield_12312328": null,
        "customfield_12312329": null,
        "customfield_12312330": null,
        "customfield_12312331": null,
        "customfield_12312332": null,
        "customfield_12312333": null,
        "customfield_12312334": null,
        "customfield_12312335": null,
        "customfield_12312336": null,
        "customfield_12312337": null,
        "customfield_12312338": null,
        "customfield_12312339": null,
        "customfield_12312340": null,
        "customfield_12312341": null,
        "customfield_12312520": null,
        "customfield_12312521": "Thu Aug 09 13:55:33 UTC 2018",
        "customfield_12312720": null,
        "customfield_12312823": null,
        "customfield_12312920": null,
        "customfield_12312921": null,
        "customfield_12312923": null,
        "customfield_12313422": "false",
        "customfield_12313520": null,
        "description": "*STEP 1. Create test data*\r\n\r\n{code}\r\ncreate table t1 (id int) ROW FORMAT DELIMITED FIELDS TERMINATED BY  \",\";\r\ncreate table t2 (id int) ROW FORMAT DELIMITED FIELDS TERMINATED BY  \",\";\r\n{code}\r\n\r\nGenerate 10 000 000 lines of random data\r\n\r\n{code}\r\npackage com.test.app;\r\n\r\nimport java.io.FileNotFoundException;\r\nimport java.io.PrintWriter;\r\nimport java.util.concurrent.ThreadLocalRandom;\r\n\r\npublic class App {\r\n  public static void main(String[] args) throws FileNotFoundException {\r\n    try (PrintWriter out = new PrintWriter(\"table.data\");) {\r\n      int min = 0;\r\n      int max = 10_000;\r\n      int numRows = 10_000_000;\r\n      for (int i = 0; i <= numRows - 1; i++){\r\n        int randomNum = ThreadLocalRandom.current().nextInt(min, max + 1);\r\n        out.println(randomNum);\r\n      }\r\n    }\r\n  }\r\n}\r\n{code}\r\n\r\nUpload data to Hive tables\r\n\r\n{code}\r\nload data local inpath '/home/myuser/table.data' into table t1;\r\nload data local inpath '/home/myuser/table.data' into table t2;\r\n{code}\r\n\r\n*STEP 2. Configure transactions in hive-site.xml*\r\n\r\n{code}\r\n<!-- Transactions -->\r\n\r\n   <property>\r\n      <name>hive.exec.dynamic.partition.mode<\/name>\r\n      <value>nonstrict<\/value>\r\n   <\/property>\r\n   <property>\r\n      <name>hive.support.concurrency<\/name>\r\n      <value>true<\/value>\r\n   <\/property>\r\n   <property>\r\n      <name>hive.enforce.bucketing<\/name>\r\n      <value>true<\/value>\r\n   <\/property>\r\n   <property>\r\n      <name>hive.txn.manager<\/name>\r\n      <value>org.apache.hadoop.hive.ql.lockmgr.DbTxnManager<\/value>\r\n   <\/property>\r\n   <property>\r\n      <name>hive.compactor.initiator.on<\/name>\r\n      <value>true<\/value>\r\n   <\/property>\r\n   <property>\r\n      <name>hive.compactor.worker.threads<\/name>\r\n      <value>1<\/value>\r\n   <\/property>\r\n{code}\r\n\r\n*STEP 3. Configure hive.txn.timeout in hive-site.xml*\r\n\r\n{code}\r\n<!-- Delegation token issue -->\r\n   <property>\r\n      <name>hive.txn.timeout<\/name>\r\n      <value>10s<\/value>\r\n   <\/property>\r\n{code}\r\n\r\n*STEP 4. Connect via beeline to HS2 with KERBEROS*\r\n\r\n{code}\r\n!connect jdbc:hive2://node8.cluster:10000/default;principal=myuser/node8.cluster@NODE8;ssl=true;sslTrustStore=/opt/myuser/conf/ssl_truststore\r\n{code}\r\n\r\n{code}\r\nselect count(*) from t1;\r\n{code}\r\n\r\n*STEP 5. Close connection and reconnect*\r\n\r\n{code}\r\n!close\r\n{code}\r\n\r\n{code}\r\n!connect jdbc:hive2://node8.cluster:10000/default;principal=myuser/node8.cluster@NODE8;ssl=true;sslTrustStore=/opt/myuser/conf/ssl_truststore\r\n{code}\r\n\r\n*STEP 6. Perform long playing query*\r\n\r\nThis query lasts about 600s\r\n\r\n{code}\r\nselect count(*) from t1 join t2 on t1.id = t2.id;\r\n{code}\r\n\r\n\r\n*EXPECTED RESULT*\r\n\r\nQuery finishes successfully\r\n\r\n*ACTUAL RESULT*\r\n\r\n{code}\r\n2018-05-17T13:54:54,921 ERROR [pool-7-thread-10] transport.TSaslTransport: SASL negotiation failure\r\njavax.security.sasl.SaslException: DIGEST-MD5: IO error acquiring password\r\n        at com.sun.security.sasl.digest.DigestMD5Server.validateClientResponse(DigestMD5Server.java:598) \r\n        at com.sun.security.sasl.digest.DigestMD5Server.evaluateResponse(DigestMD5Server.java:244)\r\n        at org.apache.thrift.transport.TSaslTransport$SaslParticipant.evaluateChallengeOrResponse(TSaslTransport.java:539) \r\n        at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:283)\r\n        at org.apache.thrift.transport.TSaslServerTransport.open(TSaslServerTransport.java:41) \r\n        at org.apache.thrift.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:216) \r\n        at org.apache.hadoop.hive.thrift.HadoopThriftAuthBridge$Server$TUGIAssumingTransportFactory$1.run(HadoopThriftAuthBridge.java:663) \r\n        at org.apache.hadoop.hive.thrift.HadoopThriftAuthBridge$Server$TUGIAssumingTransportFactory$1.run(HadoopThriftAuthBridge.java:660) \r\n        at java.security.AccessController.doPrivileged(Native Method) \r\n        at javax.security.auth.Subject.doAs(Subject.java:360)\r\n        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1613) \r\n        at org.apache.hadoop.hive.thrift.HadoopThriftAuthBridge$Server$TUGIAssumingTransportFactory.getTransport(HadoopThriftAuthBridge.java:660) \r\n        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:269)\r\n        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) \r\n        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) \r\n        at java.lang.Thread.run(Thread.java:748)\r\nCaused by: org.apache.hadoop.security.token.SecretManager$InvalidToken: token expired or does not exist: owner=myuser, renewer=myuser, realUser=, issueDate=1526565229297, maxDate=1527170029297, sequenceNumber=1, masterKeyId=1\r\n        at org.apache.hadoop.hive.thrift.TokenStoreDelegationTokenSecretManager.retrievePassword(TokenStoreDelegationTokenSecretManager.java:104) \r\n        at org.apache.hadoop.hive.thrift.TokenStoreDelegationTokenSecretManager.retrievePassword(TokenStoreDelegationTokenSecretManager.java:56)\r\n        at org.apache.hadoop.hive.thrift.HadoopThriftAuthBridge$Server$SaslDigestCallbackHandler.getPassword(HadoopThriftAuthBridge.java:472)\r\n        at org.apache.hadoop.hive.thrift.HadoopThriftAuthBridge$Server$SaslDigestCallbackHandler.handle(HadoopThriftAuthBridge.java:503) \r\n        at com.sun.security.sasl.digest.DigestMD5Server.validateClientResponse(DigestMD5Server.java:589)\r\n        ... 15 more\r\n2018-05-17T13:54:54,966 ERROR [pool-7-thread-10] server.TThreadPoolServer: Error occurred during processing of message.\r\njava.lang.RuntimeException: org.apache.thrift.transport.TTransportException: DIGEST-MD5: IO error acquiring password\r\n        at org.apache.thrift.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:219) \r\n        at org.apache.hadoop.hive.thrift.HadoopThriftAuthBridge$Server$TUGIAssumingTransportFactory$1.run(HadoopThriftAuthBridge.java:663) \r\n        at org.apache.hadoop.hive.thrift.HadoopThriftAuthBridge$Server$TUGIAssumingTransportFactory$1.run(HadoopThriftAuthBridge.java:660)\r\n        at java.security.AccessController.doPrivileged(Native Method) \r\n        at javax.security.auth.Subject.doAs(Subject.java:360)\r\n        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1613) \r\n        at org.apache.hadoop.hive.thrift.HadoopThriftAuthBridge$Server$TUGIAssumingTransportFactory.getTransport(HadoopThriftAuthBridge.java:660) \r\n        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:269)\r\n        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) \r\n        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\r\n        at java.lang.Thread.run(Thread.java:748) \r\nCaused by: org.apache.thrift.transport.TTransportException: DIGEST-MD5: IO error acquiring password\r\n        at org.apache.thrift.transport.TSaslTransport.sendAndThrowMessage(TSaslTransport.java:232) \r\n        at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:316) \r\n        at org.apache.thrift.transport.TSaslServerTransport.open(TSaslServerTransport.java:41) \r\n        at org.apache.thrift.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:216) \r\n        ... 10 more\r\n{code}\r\n\r\n\r\n*ROOT-CAUSE*\r\n\r\nHS2 uses cancelled delegation token to connect to metastore. From logs\r\n\r\n1. Metastore creates delegation token (issueDate=1526565229297)\r\n\r\n{code}\r\n2018-05-17T13:53:49,297  INFO [pool-7-thread-3] delegation.AbstractDelegationTokenSecretManager: Creating password for identifier: owner=myuser, renewer=myuser, realUser=, issueDate=1526565229297, m$\r\n2018-05-17T13:53:50,789  INFO [Thread-18] txn.TxnHandler: 'Cleaner' locked by 'node8.cluster'\r\n2018-05-17T13:53:50,793  INFO [Thread-18] txn.TxnHandler: 'Cleaner' unlocked by 'node8.cluster'\r\n2018-05-17T13:53:54,840  INFO [pool-7-thread-4] metastore.HiveMetaStore: 3: Opening raw store with implementation class:org.apache.hadoop.hive.metastore.ObjectStore\r\n{code}\r\n\r\n2. Metastore cancels delegation token (issueDate=1526565229297)\r\n\r\n{code}\r\n2018-05-17T13:54:32,380  INFO [pool-7-thread-4] thrift.TokenStoreDelegationTokenSecretManager: Token cancelation requested for identifier: owner=mapr, renewer=mapr, realUser=, issueDate=1526565229297, maxDate=1527170029297,$\r\n2018-05-17T13:54:32,416  INFO [pool-7-thread-4] metastore.HiveMetaStore: 3: Cleaning up thread local RawStore...\r\n{code}\r\n\r\n3. HS2 uses canceled delegation token and crashes (issueDate=1526565229297):\r\n\r\n{code}\r\n2018-05-17T13:54:54,921 ERROR [pool-7-thread-10] transport.TSaslTransport: SASL negotiation failure\r\njavax.security.sasl.SaslException: DIGEST-MD5: IO error acquiring password\r\n        at com.sun.security.sasl.digest.DigestMD5Server.validateClientResponse(DigestMD5Server.java:598) \r\n        at com.sun.security.sasl.digest.DigestMD5Server.evaluateResponse(DigestMD5Server.java:244)\r\n        at org.apache.thrift.transport.TSaslTransport$SaslParticipant.evaluateChallengeOrResponse(TSaslTransport.java:539) \r\n        at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:283)\r\n        at org.apache.thrift.transport.TSaslServerTransport.open(TSaslServerTransport.java:41) \r\n        at org.apache.thrift.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:216) \r\n        at org.apache.hadoop.hive.thrift.HadoopThriftAuthBridge$Server$TUGIAssumingTransportFactory$1.run(HadoopThriftAuthBridge.java:663) \r\n        at org.apache.hadoop.hive.thrift.HadoopThriftAuthBridge$Server$TUGIAssumingTransportFactory$1.run(HadoopThriftAuthBridge.java:660) \r\n        at java.security.AccessController.doPrivileged(Native Method) \r\n        at javax.security.auth.Subject.doAs(Subject.java:360)\r\n        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1613) \r\n        at org.apache.hadoop.hive.thrift.HadoopThriftAuthBridge$Server$TUGIAssumingTransportFactory.getTransport(HadoopThriftAuthBridge.java:660) \r\n        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:269)\r\n        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) \r\n        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) \r\n        at java.lang.Thread.run(Thread.java:748)\r\nCaused by: org.apache.hadoop.security.token.SecretManager$InvalidToken: token expired or does not exist: owner=myuser, renewer=myuser, realUser=, issueDate=1526565229297, maxDate=1527170029297, sequenceNumber=1, masterKeyId=1\r\n        at org.apache.hadoop.hive.thrift.TokenStoreDelegationTokenSecretManager.retrievePassword(TokenStoreDelegationTokenSecretManager.java:104)\r\n{code}\r\n\r\n\r\n*WORKAROUND*\r\n\r\nFrom Hive sources:\r\n\r\n{code}\r\nheartBeatInterval = HIVE_TXN_TIMEOUT / 2.\r\n{code}\r\n\r\nSo to skip HB during job one needs to set\r\n\r\n{code}\r\nHIVE_TXN_TIMEOUT = (max_job_duration * 2) * 1.25.\r\n{code}\r\n\r\nHere I added 1.25 factor to be sure there is no HB. In my case max_job_duration = ~600s, then \r\n\r\n{code}\r\nHIVE_TXN_TIMEOUT = 600s * 2 * 1.25 = 1500s\r\n{code}\r\n\r\nWhen I {{set hive.txn.timeout}} = 1500s issue was gone on my local env.\r\n\r\nFYI [~isnogood], [~ashutoshc]\r\n",
        "duedate": null,
        "environment": null,
        "fixVersions": [],
        "issuelinks": [
            {
                "id": "12534926",
                "outwardIssue": {
                    "fields": {
                        "issuetype": {
                            "avatarId": 21133,
                            "description": "A problem which impairs or prevents the functions of the product.",
                            "iconUrl": "https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype",
                            "id": "1",
                            "name": "Bug",
                            "self": "https://issues.apache.org/jira/rest/api/2/issuetype/1",
                            "subtask": false
                        },
                        "priority": {
                            "iconUrl": "https://issues.apache.org/jira/images/icons/priorities/major.svg",
                            "id": "3",
                            "name": "Major",
                            "self": "https://issues.apache.org/jira/rest/api/2/priority/3"
                        },
                        "status": {
                            "description": "The issue is considered finished, the resolution is correct. Issues which are not closed can be reopened.",
                            "iconUrl": "https://issues.apache.org/jira/images/icons/statuses/closed.png",
                            "id": "6",
                            "name": "Closed",
                            "self": "https://issues.apache.org/jira/rest/api/2/status/6",
                            "statusCategory": {
                                "colorName": "green",
                                "id": 3,
                                "key": "done",
                                "name": "Done",
                                "self": "https://issues.apache.org/jira/rest/api/2/statuscategory/3"
                            }
                        },
                        "summary": "Make DbTxnManager use Metastore client consistently with callers"
                    },
                    "id": "13043775",
                    "key": "HIVE-15950",
                    "self": "https://issues.apache.org/jira/rest/api/2/issue/13043775"
                },
                "self": "https://issues.apache.org/jira/rest/api/2/issueLink/12534926",
                "type": {
                    "id": "10030",
                    "inward": "is related to",
                    "name": "Reference",
                    "outward": "relates to",
                    "self": "https://issues.apache.org/jira/rest/api/2/issueLinkType/10030"
                }
            },
            {
                "id": "12534513",
                "outwardIssue": {
                    "fields": {
                        "issuetype": {
                            "avatarId": 21133,
                            "description": "A problem which impairs or prevents the functions of the product.",
                            "iconUrl": "https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype",
                            "id": "1",
                            "name": "Bug",
                            "self": "https://issues.apache.org/jira/rest/api/2/issuetype/1",
                            "subtask": false
                        },
                        "priority": {
                            "iconUrl": "https://issues.apache.org/jira/images/icons/priorities/major.svg",
                            "id": "3",
                            "name": "Major",
                            "self": "https://issues.apache.org/jira/rest/api/2/priority/3"
                        },
                        "status": {
                            "description": "The issue is considered finished, the resolution is correct. Issues which are not closed can be reopened.",
                            "iconUrl": "https://issues.apache.org/jira/images/icons/statuses/closed.png",
                            "id": "6",
                            "name": "Closed",
                            "self": "https://issues.apache.org/jira/rest/api/2/status/6",
                            "statusCategory": {
                                "colorName": "green",
                                "id": 3,
                                "key": "done",
                                "name": "Done",
                                "self": "https://issues.apache.org/jira/rest/api/2/statuscategory/3"
                            }
                        },
                        "summary": "DBTokenStore fails to connect in Kerberos enabled remote HMS environment"
                    },
                    "id": "13096611",
                    "key": "HIVE-17368",
                    "self": "https://issues.apache.org/jira/rest/api/2/issue/13096611"
                },
                "self": "https://issues.apache.org/jira/rest/api/2/issueLink/12534513",
                "type": {
                    "id": "10030",
                    "inward": "is related to",
                    "name": "Reference",
                    "outward": "relates to",
                    "self": "https://issues.apache.org/jira/rest/api/2/issueLinkType/10030"
                }
            }
        ],
        "issuetype": {
            "avatarId": 21133,
            "description": "A problem which impairs or prevents the functions of the product.",
            "iconUrl": "https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype",
            "id": "1",
            "name": "Bug",
            "self": "https://issues.apache.org/jira/rest/api/2/issuetype/1",
            "subtask": false
        },
        "labels": [],
        "lastViewed": null,
        "priority": {
            "iconUrl": "https://issues.apache.org/jira/images/icons/priorities/blocker.svg",
            "id": "1",
            "name": "Blocker",
            "self": "https://issues.apache.org/jira/rest/api/2/priority/1"
        },
        "progress": {
            "progress": 0,
            "total": 0
        },
        "project": {
            "avatarUrls": {
                "16x16": "https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=12310843&avatarId=11935",
                "24x24": "https://issues.apache.org/jira/secure/projectavatar?size=small&pid=12310843&avatarId=11935",
                "32x32": "https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=12310843&avatarId=11935",
                "48x48": "https://issues.apache.org/jira/secure/projectavatar?pid=12310843&avatarId=11935"
            },
            "id": "12310843",
            "key": "HIVE",
            "name": "Hive",
            "projectCategory": {
                "description": "Scalable Distributed Computing",
                "id": "10292",
                "name": "Hadoop",
                "self": "https://issues.apache.org/jira/rest/api/2/projectCategory/10292"
            },
            "self": "https://issues.apache.org/jira/rest/api/2/project/12310843"
        },
        "reporter": {
            "active": true,
            "avatarUrls": {
                "16x16": "https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=osayankin&avatarId=34533",
                "24x24": "https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=osayankin&avatarId=34533",
                "32x32": "https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=osayankin&avatarId=34533",
                "48x48": "https://issues.apache.org/jira/secure/useravatar?ownerId=osayankin&avatarId=34533"
            },
            "displayName": "Oleksiy Sayankin",
            "key": "osayankin",
            "name": "osayankin",
            "self": "https://issues.apache.org/jira/rest/api/2/user?username=osayankin",
            "timeZone": "Etc/UTC"
        },
        "resolution": null,
        "resolutiondate": null,
        "status": {
            "description": "A patch for this issue has been uploaded to JIRA by a contributor.",
            "iconUrl": "https://issues.apache.org/jira/images/icons/statuses/document.png",
            "id": "10002",
            "name": "Patch Available",
            "self": "https://issues.apache.org/jira/rest/api/2/status/10002",
            "statusCategory": {
                "colorName": "yellow",
                "id": 4,
                "key": "indeterminate",
                "name": "In Progress",
                "self": "https://issues.apache.org/jira/rest/api/2/statuscategory/4"
            }
        },
        "subtasks": [],
        "summary": "HeartBeat thread uses cancelled delegation token while connecting to meta on KERBEROS cluster",
        "timeestimate": null,
        "timeoriginalestimate": null,
        "timespent": null,
        "updated": "2018-08-09T13:55:33.000+0000",
        "versions": [
            {
                "archived": false,
                "id": "12340268",
                "name": "3.0.0",
                "releaseDate": "2018-05-21",
                "released": true,
                "self": "https://issues.apache.org/jira/rest/api/2/version/12340268"
            },
            {
                "archived": false,
                "id": "12342053",
                "name": "2.3.2",
                "releaseDate": "2017-11-13",
                "released": true,
                "self": "https://issues.apache.org/jira/rest/api/2/version/12342053"
            },
            {
                "archived": false,
                "description": "",
                "id": "12343014",
                "name": "3.1.0",
                "releaseDate": "2018-07-30",
                "released": true,
                "self": "https://issues.apache.org/jira/rest/api/2/version/12343014"
            }
        ],
        "votes": {
            "hasVoted": false,
            "self": "https://issues.apache.org/jira/rest/api/2/issue/HIVE-19587/votes",
            "votes": 1
        },
        "watches": {
            "isWatching": false,
            "self": "https://issues.apache.org/jira/rest/api/2/issue/HIVE-19587/watchers",
            "watchCount": 5
        },
        "workratio": -1
    },
    "id": "13160070",
    "key": "HIVE-19587",
    "self": "https://issues.apache.org/jira/rest/api/2/issue/13160070"
}