{"expand":"renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations","id":"12483810","self":"https://issues.apache.org/jira/rest/api/2/issue/12483810","key":"AMQ-1063","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype","name":"Bug","subtask":false,"avatarId":21133},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/12311210","id":"12311210","key":"AMQ","name":"ActiveMQ","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=12311210&avatarId=10011","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=12311210&avatarId=10011","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=12311210&avatarId=10011","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=12311210&avatarId=10011"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/11160","id":"11160","description":"ActiveMQ","name":"ActiveMQ"}},"fixVersions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12326455","id":"12326455","name":"5.9.1","archived":false,"released":true,"releaseDate":"2014-04-04"},{"self":"https://issues.apache.org/jira/rest/api/2/version/12324950","id":"12324950","name":"5.10.0","archived":false,"released":true,"releaseDate":"2014-06-10"}],"aggregatetimespent":null,"resolution":{"self":"https://issues.apache.org/jira/rest/api/2/resolution/1","id":"1","description":"A fix for this issue is checked into the tree and tested.","name":"Fixed"},"customfield_12312322":null,"customfield_12310220":"2006-11-20T06:24:31.000+0000","customfield_12312520":null,"customfield_12312323":null,"customfield_12312521":"Mon Dec 09 17:04:31 UTC 2013","customfield_12310420":"84728","customfield_12312320":null,"customfield_12310222":"1_*:*_1_*:*_219493624392_*|*_5_*:*_2_*:*_3131045507_*|*_4_*:*_1_*:*_1465388","customfield_12312321":null,"resolutiondate":"2013-12-09T17:04:31.253+0000","workratio":-1,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312923":null,"customfield_12312326":null,"customfield_12312920":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312921":null,"customfield_12312324":null,"customfield_12312720":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/AMQ-1063/watchers","watchCount":17,"isWatching":false},"created":"2006-11-20T00:28:56.000+0000","priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.svg","name":"Major","id":"3"},"labels":[],"customfield_12312333":null,"customfield_12312334":null,"customfield_12313422":"false","customfield_12310310":"1.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"customfield_12311120":null,"customfield_12312330":null,"versions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12315617","id":"12315617","description":"","name":"5.0.0","archived":false,"released":true,"releaseDate":"2007-12-17"}],"issuelinks":[],"customfield_12312339":null,"assignee":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=davsclaus","name":"davsclaus","key":"davsclaus","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=davsclaus&avatarId=15835","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=davsclaus&avatarId=15835","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=davsclaus&avatarId=15835","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=davsclaus&avatarId=15835"},"displayName":"Claus Ibsen","active":true,"timeZone":"Europe/Berlin"},"customfield_12312337":null,"customfield_12312338":null,"updated":"2014-04-02T22:20:30.764+0000","customfield_12312335":null,"customfield_12312336":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/5","description":"A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/resolved.png","name":"Resolved","id":"5","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Done"}},"components":[{"self":"https://issues.apache.org/jira/rest/api/2/component/12313892","id":"12313892","name":"Broker"}],"timeoriginalestimate":null,"customfield_12310080":null,"description":"I am running trunk using JDBC against MySQL 5.0.27.  I am seeing the above mentioned IOException.  Do not have specific instructions on how to reproduce at the current time, but I was using durable subscriptions with the store durable cursor if that helps.  (I'll post if I find out more information.)\n\n      <persistenceAdapter>\n   \n      <journaledJDBC journalLogFiles=\"5\" dataDirectory=\"../activemq-data\" dataSource=\"#mysql-ds\"/>\n\n    </persistenceAdapter>\n\n  <bean id=\"mysql-ds\" class=\"org.apache.commons.dbcp.BasicDataSource\" destroy-method=\"close\">\n    <property name=\"driverClassName\" value=\"com.mysql.jdbc.Driver\"/>\n    <property name=\"url\" value=\"jdbc:mysql://localhost/activemq?relaxAutoCommit=true\"/>\n    <property name=\"username\" value=\"*** OMITTED ***\"/>\n    <property name=\"password\" value=\"*** OMITTED *** \"/>\n    <property name=\"poolPreparedStatements\" value=\"true\"/>\n  </bean>  \n\nLog trace:\n\n2006-11-19 19:19:48,078 [/127.0.0.1:4898] DEBUG JournalPersistenceAdapter      - Waking for checkpoint to complete.\n2006-11-19 19:19:48,078 [eckpoint Worker] DEBUG JournalPersistenceAdapter      - Checkpoint started.\n2006-11-19 19:19:48,078 [eckpoint Worker] ERROR JournalPersistenceAdapter      - Failed to checkpoint a message store: java.util.concurrent.ExecutionException: java.io.IOException: Already started.\njava.util.concurrent.ExecutionException: java.io.IOException: Already started.\n\tat java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:205)\n\tat java.util.concurrent.FutureTask.get(FutureTask.java:80)\n\tat org.apache.activemq.store.journal.JournalPersistenceAdapter.doCheckpoint(JournalPersistenceAdapter.java:386)\n\tat org.apache.activemq.store.journal.JournalPersistenceAdapter$2.iterate(JournalPersistenceAdapter.java:129)\n\tat org.apache.activemq.thread.DedicatedTaskRunner.runTask(DedicatedTaskRunner.java:88)\n\tat org.apache.activemq.thread.DedicatedTaskRunner.access$0(DedicatedTaskRunner.java:76)\n\tat org.apache.activemq.thread.DedicatedTaskRunner$1.run(DedicatedTaskRunner.java:39)\nCaused by: java.io.IOException: Already started.\n\tat org.apache.activemq.store.jdbc.TransactionContext.begin(TransactionContext.java:145)\n\tat org.apache.activemq.store.jdbc.JDBCPersistenceAdapter.beginTransaction(JDBCPersistenceAdapter.java:358)\n\tat org.apache.activemq.store.journal.JournalPersistenceAdapter.beginTransaction(JournalPersistenceAdapter.java:189)\n\tat org.apache.activemq.util.TransactionTemplate.run(TransactionTemplate.java:41)\n\tat org.apache.activemq.store.journal.JournalMessageStore.checkpoint(JournalMessageStore.java:247)\n\tat org.apache.activemq.store.journal.JournalTopicMessageStore.checkpoint(JournalTopicMessageStore.java:162)\n\tat org.apache.activemq.store.journal.JournalPersistenceAdapter$5.call(JournalPersistenceAdapter.java:373)\n\tat java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:269)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:123)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)\n\tat java.lang.Thread.run(Thread.java:595)\n2006-11-19 19:19:48,109 [eckpoint Worker] DEBUG JournalPersistenceAdapter      - Checkpoint done.","customfield_10010":null,"timetracking":{},"customfield_12312026":null,"customfield_12312023":null,"customfield_12312024":null,"customfield_12312340":null,"attachment":[{"self":"https://issues.apache.org/jira/rest/api/2/attachment/12461693","id":"12461693","filename":"activemq.log.zip","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hondong","name":"hondong","key":"hondong","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Hondong","active":true,"timeZone":"Etc/UTC"},"created":"2010-05-06T18:06:05.700+0000","size":377329,"mimeType":"application/zip","content":"https://issues.apache.org/jira/secure/attachment/12461693/activemq.log.zip"}],"aggregatetimeestimate":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12312022":null,"customfield_12310041":null,"customfield_12310921":null,"customfield_12310920":"59868","customfield_12312823":null,"summary":"Journaled JDBC checkpoint fails with java.io.IOException: Already started.","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=jk%40penguinsfan.com","name":"jk@penguinsfan.com","key":"jk@penguinsfan.com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"jk@penguinsfan.com","active":true,"timeZone":"Etc/UTC"},"subtasks":[],"customfield_12310291":null,"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=jk%40penguinsfan.com","name":"jk@penguinsfan.com","key":"jk@penguinsfan.com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"jk@penguinsfan.com","active":true,"timeZone":"Etc/UTC"},"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":0},"customfield_12311024":null,"environment":"Windows XP Professional, JVM 1.5.0_09, MySQL 5.0.27","customfield_12313520":null,"customfield_12311020":null,"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"comment":{"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/12938484","id":"12938484","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kgallo","name":"kgallo","key":"kgallo","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Ken Gallo","active":true,"timeZone":"Etc/UTC"},"body":"Do you have the mysql-connector-java.jar in the lib folder?\nDo you have an activemq schema in your db?\n\nIt works in my Windows XP, Java 1.5.0_06, MySQL 5.0.24 environment.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kgallo","name":"kgallo","key":"kgallo","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Ken Gallo","active":true,"timeZone":"Etc/UTC"},"created":"2006-11-20T06:24:31.000+0000","updated":"2006-11-20T06:24:31.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/12938739","id":"12938739","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=arboz","name":"arboz","key":"arboz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Artem","active":true,"timeZone":"Etc/UTC"},"body":"I have the same problem with MS SQL 2005. \nSymptomis the same as was described - plus \nmany durable queue produsers and consumers, large queue size.\nException occurs suddenly, after 6-7-24 hours of fine work.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=arboz","name":"arboz","key":"arboz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Artem","active":true,"timeZone":"Etc/UTC"},"created":"2006-12-26T22:03:17.000+0000","updated":"2006-12-26T22:03:17.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/12938728","id":"12938728","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=arboz","name":"arboz","key":"arboz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Artem","active":true,"timeZone":"Etc/UTC"},"body":"Can I use JDBC Persistence without Journaling as walkaround? \nThank you for replay, It's very critical for me. Thank you.\n\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=arboz","name":"arboz","key":"arboz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Artem","active":true,"timeZone":"Etc/UTC"},"created":"2006-12-26T22:09:22.000+0000","updated":"2006-12-26T22:09:22.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/12938902","id":"12938902","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=frank1russo","name":"frank1russo","key":"frank1russo","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Frank Russo","active":true,"timeZone":"Etc/UTC"},"body":"We are having the same issue using Oracle. Here is our config:\n\n        <persistenceAdapter>\n                <journaledJDBC journalLogFiles=\"5\" dataDirectory=\"${activemq.home}/activemq-data\" dataSource=\"#oracle-ds\"/>\n        </persistenceAdapter>\n        \n        <bean id=\"oracle-ds\" class=\"org.apache.commons.dbcp.BasicDataSource\" destroy-method=\"close\">\n                <property name=\"driverClassName\" value=\"oracle.jdbc.driver.OracleDriver\"/>\n                <property name=\"url\" value=\"***\"/>\n                <property name=\"username\" value=\"***\"/>\n                <property name=\"password\" value=\"***\"/>\n                <property name=\"poolPreparedStatements\" value=\"true\"/>\n        </bean>\n\nAny ideas what could cause this?\n\nThanks...","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=frank1russo","name":"frank1russo","key":"frank1russo","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Frank Russo","active":true,"timeZone":"Etc/UTC"},"created":"2007-02-14T14:49:19.559+0000","updated":"2007-02-14T14:49:19.559+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/12936404","id":"12936404","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=jstrachan","name":"jstrachan","key":"jstrachan","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"james strachan","active":true,"timeZone":"Etc/UTC"},"body":"updated affected version","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=jstrachan","name":"jstrachan","key":"jstrachan","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"james strachan","active":true,"timeZone":"Etc/UTC"},"created":"2007-06-12T10:28:54.591+0000","updated":"2007-06-12T10:28:54.591+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/12936631","id":"12936631","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=vpesochi","name":"vpesochi","key":"vpesochi","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Vadim Pesochinskiy","active":true,"timeZone":"Etc/UTC"},"body":"And we also have been having \"this\" issue since Feb 2007 in 4.1.0 on Derby\n\nOther people, also having this issue:\n\nhttp://www.nabble.com/failed-to-checkpoint-a-message-store--tf3156345s2354.html#a8752776\nhttp://www.nabble.com/Failed-to-checkpoint-a-messaeg-store-tf1758021s2354.html#a4781889\n\n\nConfig:\n\n        <persistenceAdapter>\n            <journaledJDBC journalLogFiles=\"5\" dataDirectory=\"${messageStoreDir}\" dataSource=\"#derby-ds\"/>\n        </persistenceAdapter>\n    <bean id=\"derby-ds\" class=\"org.apache.derby.jdbc.EmbeddedDataSource\">\n        <property name=\"databaseName\" value=\"derbydb\"/>\n        <property name=\"createDatabase\" value=\"create\"/>\n    </bean>\n\nSEVERE: Failed to checkpoint a message store: edu.emory.mathcs.backport.java.util.concurrent.ExecutionException: java.io.IOException: Not started.\nedu.emory.mathcs.backport.java.util.concurrent.ExecutionException: java.io.IOException: Not started.\n at edu.emory.mathcs.backport.java.util.concurrent.FutureTask.getResult(FutureTask.java:299)\n at edu.emory.mathcs.backport.java.util.concurrent.FutureTask.get(FutureTask.java:118)\n at org.apache.activemq.store.journal.JournalPersistenceAdapter.doCheckpoint(JournalPersistenceAdapter.java:386)\n at org.apache.activemq.store.journal.JournalPersistenceAdapter$2.iterate(JournalPersistenceAdapter.java:129)\n at org.apache.activemq.thread.DedicatedTaskRunner.runTask(DedicatedTaskRunner.java:88)\n at org.apache.activemq.thread.DedicatedTaskRunner.access$000(DedicatedTaskRunner.java:25)\n at org.apache.activemq.thread.DedicatedTaskRunner$1.run(DedicatedTaskRunner.java:39)\nCaused by: java.io.IOException: Not started.\n at org.apache.activemq.store.jdbc.TransactionContext.rollback(TransactionContext.java:168)\n at org.apache.activemq.store.jdbc.JDBCPersistenceAdapter.rollbackTransaction(JDBCPersistenceAdapter.java:368)\n at org.apache.activemq.store.journal.JournalPersistenceAdapter.rollbackTransaction(JournalPersistenceAdapter.java:197)\n at org.apache.activemq.util.TransactionTemplate.run(TransactionTemplate.java:62)\n at org.apache.activemq.store.journal.JournalMessageStore.checkpoint(JournalMessageStore.java:247)\n at org.apache.activemq.store.journal.JournalMessageStore.checkpoint(JournalMessageStore.java:221)\n at org.apache.activemq.store.journal.JournalPersistenceAdapter$4.call(JournalPersistenceAdapter.java:356)\n at edu.emory.mathcs.backport.java.util.concurrent.FutureTask.run(FutureTask.java:176)\n at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)\n at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)\n at java.lang.Thread.run(Thread.java:595)\norg.apache.activemq.store.journal.JournalPersistenceAdapter doCheckpoint\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=vpesochi","name":"vpesochi","key":"vpesochi","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Vadim Pesochinskiy","active":true,"timeZone":"Etc/UTC"},"created":"2007-07-31T19:44:04.181+0000","updated":"2007-07-31T19:44:04.181+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/12936545","id":"12936545","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=vpesochi","name":"vpesochi","key":"vpesochi","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Vadim Pesochinskiy","active":true,"timeZone":"Etc/UTC"},"body":"After that happens the first time I keep seeing this every second or so about 30 times and after that AMQ is dead. No messages are delivered anymore. Once in this state I cannot pull up messages via jconsole / operations / Browse As Table.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=vpesochi","name":"vpesochi","key":"vpesochi","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Vadim Pesochinskiy","active":true,"timeZone":"Etc/UTC"},"created":"2007-07-31T19:50:42.734+0000","updated":"2007-07-31T19:50:42.734+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/12939169","id":"12939169","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=twalters","name":"twalters","key":"twalters","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Tim Walters","active":true,"timeZone":"Etc/UTC"},"body":"I've been looking at the 4.1.1 code for checkpointing and think I've found a problem.\n\nJDBC statements for copying messages to the longterm storage are handled by a TransactionContext object. If a SQLException is raised during execution of TransactionContext.commit(), the finally clause will close the JDBC connection and clear the 'inTx' flag showing a current transaction. However the exception will cause a TransactionContext.rollback() to be called, which will see the cleared 'inTx' flag and throw an exception with the 'Not started' message in the logs above. Also, the JDBC rollback() and statement close() methods won't be called correctly which could cause leaks or partial data commits.\n\nJDBCPersistenceAdapter.log only logs SQL errors at the debug level, so the root cause of this problem is likely to be missing from the logs. My guess is that the different reports above might each reflect a different SQL error.\n\nIt looks like the minimal changes which should be made here are:\n\n- Log SQL errors during commit() at a error level\n- Make sure rollback() can be called after the commit() error.\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=twalters","name":"twalters","key":"twalters","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Tim Walters","active":true,"timeZone":"Etc/UTC"},"created":"2007-10-12T22:06:23.759+0000","updated":"2007-10-12T22:06:23.759+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/12940471","id":"12940471","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=guillon","name":"guillon","key":"guillon","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Benoit Guillon","active":true,"timeZone":"Etc/UTC"},"body":"Is there any known workaround to this issue ?\n\nI currently use this configuration for persistence:\n\n<persistenceAdapter>\n      <journaledJDBC journalLogFiles=\"5\" dataDirectory=\"/data/activemq-data\" dataSource=\"#datasource\" createTablesOnStartup=\"false\" useDatabaseLock=\"false\"/>\n</persistenceAdapter>\n\nThanks.\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=guillon","name":"guillon","key":"guillon","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Benoit Guillon","active":true,"timeZone":"Etc/UTC"},"created":"2008-11-10T16:39:49.106+0000","updated":"2008-11-10T16:39:49.106+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/12941123","id":"12941123","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=vkothiyal","name":"vkothiyal","key":"vkothiyal","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Vipul Kothiyal","active":true,"timeZone":"Etc/UTC"},"body":"I am getting same error messages with mysql as message store :( with AMQ 5.2.0. any workaround for this issue?","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=vkothiyal","name":"vkothiyal","key":"vkothiyal","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Vipul Kothiyal","active":true,"timeZone":"Etc/UTC"},"created":"2009-09-09T15:34:46.749+0000","updated":"2009-09-09T15:34:46.749+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/12941267","id":"12941267","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=vkothiyal","name":"vkothiyal","key":"vkothiyal","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Vipul Kothiyal","active":true,"timeZone":"Etc/UTC"},"body":"Using Jdbc persistence without jornaling seems to ahve done the trick, I know it's BAD for performace but better then the whole meesage queue getting frozen.\nAny better suggestions?\n\nCheers\nV\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=vkothiyal","name":"vkothiyal","key":"vkothiyal","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Vipul Kothiyal","active":true,"timeZone":"Etc/UTC"},"created":"2009-09-10T09:50:30.135+0000","updated":"2009-09-10T09:50:30.135+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/12940666","id":"12940666","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=subendu","name":"subendu","key":"subendu","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Subendu Dasgupta","active":true,"timeZone":"Etc/UTC"},"body":"I am facing the same issue with MySql 5.1 and activemq 5.3 (on Fuse 3.4.04) lib folder. Here is my configuration.\n\n<amq:persistenceAdapter>\n\t  <amq:journaledJDBC journalLogFiles=\"5\" dataDirectory=\"./data/activemq-data\" dataSource=\"#ors-activemq-ds\" createTablesOnStartup=\"true\" useDatabaseLock=\"false\"/> \n</amq:persistenceAdapter>\n\n<bean id=\"ors-activemq-ds\" class=\"org.apache.commons.dbcp.BasicDataSource\" destroy-method=\"close\">\n \t\t<property name=\"driverClassName\" value=\"${activemq.jdbc.driver}\" /> \n\t\t<property name=\"url\" value=\"${activemq.jdbc.url}\" /> \n\t\t<property name=\"username\" value=\"${activemq.jdbc.username}\" /> \n\t\t<property name=\"password\" value=\"${activemq.jdbc.password}\" /> \n\t\t<property name=\"poolPreparedStatements\" value=\"true\" /> \n</bean> \n\njava.util.concurrent.ExecutionException: java.io.IOException: Already started.\n        at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:222)\n        at java.util.concurrent.FutureTask.get(FutureTask.java:83)\n        at org.apache.activemq.store.journal.JournalPersistenceAdapter.doCheckpoint(JournalPersistenceAdapter.java:421)\n        at org.apache.activemq.store.journal.JournalPersistenceAdapter$1.iterate(JournalPersistenceAdapter.java:124)\n        at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:122)\n        at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:43)\n        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)\n        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)\n        at java.lang.Thread.run(Thread.java:619)\nCaused by: java.io.IOException: Already started.\n        at org.apache.activemq.store.jdbc.TransactionContext.begin(TransactionContext.java:148)\n        at org.apache.activemq.store.jdbc.JDBCPersistenceAdapter.beginTransaction(JDBCPersistenceAdapter.java:399)\n        at org.apache.activemq.store.journal.JournalPersistenceAdapter.beginTransaction(JournalPersistenceAdapter.java:216)\n        at org.apache.activemq.util.TransactionTemplate.run(TransactionTemplate.java:41)\n        at org.apache.activemq.store.journal.JournalMessageStore.checkpoint(JournalMessageStore.java:258)\n        at org.apache.activemq.store.journal.JournalMessageStore.checkpoint(JournalMessageStore.java:233)\n        at org.apache.activemq.store.journal.JournalPersistenceAdapter$4.call(JournalPersistenceAdapter.java:391)\n        at org.apache.activemq.store.journal.JournalPersistenceAdapter$4.call(JournalPersistenceAdapter.java:390)\n        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)\n        at java.util.concurrent.FutureTask.run(FutureTask.java:138)\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=subendu","name":"subendu","key":"subendu","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Subendu Dasgupta","active":true,"timeZone":"Etc/UTC"},"created":"2009-09-22T14:44:59.085+0000","updated":"2009-09-22T14:44:59.085+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/12941763","id":"12941763","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=bananeman","name":"bananeman","key":"bananeman","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Edgar Vonk","active":true,"timeZone":"Etc/UTC"},"body":"[Here|http://www.nabble.com/failed-to-checkpoint-a-message-store--td8752776.html] I read that a workaround is to just not pool prepared statements. So I have now put:\n{code}\n<property name=\"poolPreparedStatements\" value=\"false\"/>\n{code}\n\nin our (Oracle) datasource definition in activemq.xml.\n\nHas anyone else tried this? And does it really solve the issue?","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=bananeman","name":"bananeman","key":"bananeman","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Edgar Vonk","active":true,"timeZone":"Etc/UTC"},"created":"2009-10-28T09:20:05.483+0000","updated":"2009-10-28T09:20:05.483+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/12941764","id":"12941764","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=bananeman","name":"bananeman","key":"bananeman","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Edgar Vonk","active":true,"timeZone":"Etc/UTC"},"body":"I am confused. Is this the same issue as AMQ-1611 or not?\n\nAnd if so, will upgrading to ActiveMQ to 5.3.0 (we are now at 5.2.0) simply fix this issue?","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=bananeman","name":"bananeman","key":"bananeman","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Edgar Vonk","active":true,"timeZone":"Etc/UTC"},"created":"2009-10-28T10:09:56.957+0000","updated":"2009-10-28T10:09:56.957+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/12942402","id":"12942402","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=vkothiyal","name":"vkothiyal","key":"vkothiyal","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Vipul Kothiyal","active":true,"timeZone":"Etc/UTC"},"body":"^^no upgrade to 5.3.0 doesn't fix it. also <property name=\"poolPreparedStatements\" value=\"false\"/> doesn't fix it.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=vkothiyal","name":"vkothiyal","key":"vkothiyal","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Vipul Kothiyal","active":true,"timeZone":"Etc/UTC"},"created":"2010-04-15T14:59:06.162+0000","updated":"2010-04-15T14:59:06.162+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/12942409","id":"12942409","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=gtully","name":"gtully","key":"gtully","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Gary Tully","active":true,"timeZone":"Etc/UTC"},"body":"Vipul, is it reproducible? Can you upload the output of the broker with debug logging enabled, that may help","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=gtully","name":"gtully","key":"gtully","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Gary Tully","active":true,"timeZone":"Etc/UTC"},"created":"2010-04-15T15:30:13.714+0000","updated":"2010-04-15T15:30:13.714+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/12942397","id":"12942397","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=vkothiyal","name":"vkothiyal","key":"vkothiyal","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Vipul Kothiyal","active":true,"timeZone":"Etc/UTC"},"body":"Hi Gary,\nIt's an intermittent issue for us, happens every now and then, a restart of the broker fixes till next occurrence. We don't have debugging enabled in our logs, but I'll do and post the output when it happens next time around. \nCheers\nV","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=vkothiyal","name":"vkothiyal","key":"vkothiyal","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Vipul Kothiyal","active":true,"timeZone":"Etc/UTC"},"created":"2010-04-15T15:36:49.887+0000","updated":"2010-04-15T15:36:49.887+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/12942570","id":"12942570","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hondong","name":"hondong","key":"hondong","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Hondong","active":true,"timeZone":"Etc/UTC"},"body":"We even have the same Issue under ActiveMQ 4.1.2 and Oracle DS\nIt seems, that it appear under heavy Load?\n\nI´ll try to reproduce it with debugging enabled...","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hondong","name":"hondong","key":"hondong","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Hondong","active":true,"timeZone":"Etc/UTC"},"created":"2010-05-05T05:14:55.157+0000","updated":"2010-05-05T05:14:55.157+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/12942589","id":"12942589","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hondong","name":"hondong","key":"hondong","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Hondong","active":true,"timeZone":"Etc/UTC"},"body":"Hi,\n\nhere is the Log with this error in Debug Mode. \nI´ll Attach it to this issue, but I think this is the interesting part for you:\n\n2010-05-06 19:20:49,275 [5fda:6db0:61938] DEBUG AbstractRegion                 - Removing consumer: aa82a0e0-dc97-47ef-b34a-6d89a9826915:399:45359\n2010-05-06 19:20:50,289 [5fda:6db0:61938] DEBUG AbstractRegion                 - Adding consumer: aa82a0e0-dc97-47ef-b34a-6d89a9826915:399:45360\n2010-05-06 19:20:50,382 [eckpoint Worker] DEBUG JournalPersistenceAdapter      - Checkpoint started.\n2010-05-06 19:20:50,398 [5fda:6db0:61938] DEBUG AbstractRegion                 - Removing consumer: aa82a0e0-dc97-47ef-b34a-6d89a9826915:399:45360\n2010-05-06 19:20:50,585 [eckpoint Worker] ERROR JournalPersistenceAdapter      - Failed to checkpoint a message store: edu.emory.mathcs.backport.java.util.concurrent.ExecutionException: java.io.IOException: Already started.\nedu.emory.mathcs.backport.java.util.concurrent.ExecutionException: java.io.IOException: Already started.\n\tat edu.emory.mathcs.backport.java.util.concurrent.FutureTask.getResult(FutureTask.java:299)\n\tat edu.emory.mathcs.backport.java.util.concurrent.FutureTask.get(FutureTask.java:118)\n\tat org.apache.activemq.store.journal.JournalPersistenceAdapter.doCheckpoint(JournalPersistenceAdapter.java:386)\n\tat org.apache.activemq.store.journal.JournalPersistenceAdapter$2.iterate(JournalPersistenceAdapter.java:129)\n\tat org.apache.activemq.thread.DedicatedTaskRunner.runTask(DedicatedTaskRunner.java:101)\n\tat org.apache.activemq.thread.DedicatedTaskRunner.access$000(DedicatedTaskRunner.java:25)\n\tat org.apache.activemq.thread.DedicatedTaskRunner$1.run(DedicatedTaskRunner.java:39)\nCaused by: java.io.IOException: Already started.\n\tat org.apache.activemq.store.jdbc.TransactionContext.begin(TransactionContext.java:145)\n\tat org.apache.activemq.store.jdbc.JDBCPersistenceAdapter.beginTransaction(JDBCPersistenceAdapter.java:358)\n\tat org.apache.activemq.store.journal.JournalPersistenceAdapter.beginTransaction(JournalPersistenceAdapter.java:189)\n\tat org.apache.activemq.util.TransactionTemplate.run(TransactionTemplate.java:41)\n\tat org.apache.activemq.store.journal.JournalMessageStore.checkpoint(JournalMessageStore.java:247)\n\tat org.apache.activemq.store.journal.JournalMessageStore.checkpoint(JournalMessageStore.java:221)\n\tat org.apache.activemq.store.journal.JournalPersistenceAdapter$4.call(JournalPersistenceAdapter.java:356)\n\tat edu.emory.mathcs.backport.java.util.concurrent.FutureTask.run(FutureTask.java:176)\n\tat edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)\n\tat edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)\n\tat java.lang.Thread.run(Thread.java:619)\n2010-05-06 19:20:50,585 [eckpoint Worker] DEBUG JournalPersistenceAdapter      - Marking journal at: 190:18104176\n2010-05-06 19:20:50,585 [eckpoint Worker] ERROR JournalPersistenceAdapter      - Failed to mark the Journal: org.apache.activeio.journal.InvalidRecordLocationException: The location is less than the last mark.\norg.apache.activeio.journal.InvalidRecordLocationException: The location is less than the last mark.\n\tat org.apache.activeio.journal.active.JournalImpl.setMark(JournalImpl.java:340)\n\tat org.apache.activemq.store.journal.JournalPersistenceAdapter.doCheckpoint(JournalPersistenceAdapter.java:403)\n\tat org.apache.activemq.store.journal.JournalPersistenceAdapter$2.iterate(JournalPersistenceAdapter.java:129)\n\tat org.apache.activemq.thread.DedicatedTaskRunner.runTask(DedicatedTaskRunner.java:101)\n\tat org.apache.activemq.thread.DedicatedTaskRunner.access$000(DedicatedTaskRunner.java:25)\n\tat org.apache.activemq.thread.DedicatedTaskRunner$1.run(DedicatedTaskRunner.java:39)\n2010-05-06 19:20:50,585 [eckpoint Worker] DEBUG JDBCPersistenceAdapter         - Cleaning up old messages.\n2010-05-06 19:20:50,585 [eckpoint Worker] DEBUG DefaultJDBCAdapter             - Executing SQL: DELETE FROM ACTIVEMQ_MSGS WHERE ( EXPIRATION<>0 AND EXPIRATION<?) OR ID <= ( SELECT min(ACTIVEMQ_ACKS.LAST_ACKED_ID) FROM ACTIVEMQ_ACKS WHERE ACTIVEMQ_ACKS.CONTAINER=ACTIVEMQ_MSGS.CONTAINER)\n2010-05-06 19:20:50,585 [eckpoint Worker] DEBUG DefaultJDBCAdapter             - Deleted 0 old message(s).\n2010-05-06 19:20:50,585 [eckpoint Worker] DEBUG JDBCPersistenceAdapter         - Cleanup done.\n2010-05-06 19:20:50,585 [eckpoint Worker] DEBUG JournalPersistenceAdapter      - Checkpoint done.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hondong","name":"hondong","key":"hondong","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Hondong","active":true,"timeZone":"Etc/UTC"},"created":"2010-05-06T17:55:01.282+0000","updated":"2010-05-06T17:55:01.282+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/12942595","id":"12942595","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hondong","name":"hondong","key":"hondong","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Hondong","active":true,"timeZone":"Etc/UTC"},"body":"Here are the Debug Log Files...","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hondong","name":"hondong","key":"hondong","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Hondong","active":true,"timeZone":"Etc/UTC"},"created":"2010-05-06T18:06:05.819+0000","updated":"2010-05-06T18:06:05.819+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/13481287","id":"13481287","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=pnidl","name":"pnidl","key":"pnidl","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=pnidl&avatarId=16139","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=pnidl&avatarId=16139","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=pnidl&avatarId=16139","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=pnidl&avatarId=16139"},"displayName":"Petr Nídl","active":true,"timeZone":"Europe/Berlin"},"body":"I've analyzed the problem for 5.6.0 release. It happens when org.apache.activemq.store.journal.JournalPersistenceAdapter starts new transaction during checkpoint and fails to retrieve the database connection for this task. The main cause is in org.apache.activemq.store.jdbc.TransactionContext.begin() method (lines 153-159):\n\npublic void begin() throws IOException {\n  if (inTx) {\n    throw new IOException(\"Already started.\");\n  }\n  inTx = true;\n  connection = getConnection();\n}\n\nLines 157 and 158 should be switched because currently the TransactionContext instance is marked as \"inTx\" even though the getConnection() method throws an exception. From that moment the TransactionContext instance is marked as \"inTx\" forever and will never start new transaction again.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=pnidl","name":"pnidl","key":"pnidl","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=pnidl&avatarId=16139","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=pnidl&avatarId=16139","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=pnidl&avatarId=16139","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=pnidl&avatarId=16139"},"displayName":"Petr Nídl","active":true,"timeZone":"Europe/Berlin"},"created":"2012-10-22T10:16:29.261+0000","updated":"2012-10-22T10:18:04.460+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/13812324","id":"13812324","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=davsclaus","name":"davsclaus","key":"davsclaus","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=davsclaus&avatarId=15835","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=davsclaus&avatarId=15835","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=davsclaus&avatarId=15835","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=davsclaus&avatarId=15835"},"displayName":"Claus Ibsen","active":true,"timeZone":"Europe/Berlin"},"body":"Thanks for reporting.\n\nAnd Petr Nídl for the suggested fix.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=davsclaus","name":"davsclaus","key":"davsclaus","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=davsclaus&avatarId=15835","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=davsclaus&avatarId=15835","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=davsclaus&avatarId=15835","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=davsclaus&avatarId=15835"},"displayName":"Claus Ibsen","active":true,"timeZone":"Europe/Berlin"},"created":"2013-11-03T10:56:00.386+0000","updated":"2013-11-03T10:56:00.386+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/13812666","id":"13812666","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rkraus","name":"rkraus","key":"rkraus","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Radek Kraus","active":true,"timeZone":"Europe/Prague"},"body":"I'm sorry for comment to fixed issue. But IMHO the fix suggested by Petr Nidl isn't 100% correct. We already tried to use this fix. It seams, that really solved the {{java.io.IOException: Already started.}} problem. But after this fix we faced to new problems:\n# invoke a commit on Firebird connection, which is set as {{autocommit = true}} (already reported in [AMQ-4836|https://issues.apache.org/jira/browse/AMQ-4836] by Jiri Patera)\n# (*most important*) possibility to set the connection as {{autocommit = true}}, even if the connection is configured as {{autocommit = false}} on datasource level, when transaction is started ({{TransactionContext.begin()}} method is invoked), see the {{getConnection()}} method. The reason for this behavior is \"line switching\"  in suggested fix. I don't know all places and ways, where transactions are used, but IMHO it seams as problem, when the transaction is started and connection is configured as {{autocommit = true}}\n\nMaybe I miss something, but thought that this comment can be useful.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rkraus","name":"rkraus","key":"rkraus","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Radek Kraus","active":true,"timeZone":"Europe/Prague"},"created":"2013-11-04T07:53:03.782+0000","updated":"2013-11-04T07:53:03.782+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/13843306","id":"13843306","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=gtully","name":"gtully","key":"gtully","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Gary Tully","active":true,"timeZone":"Etc/UTC"},"body":"there is indeed a problem with this fix as pointed out above.\n\ngetConnection depends on the inTx flag.\n\nmaybe the correct fix is to clear the inTx flag in TransactionContext.getConnection() before we throw the ioe.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=gtully","name":"gtully","key":"gtully","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Gary Tully","active":true,"timeZone":"Etc/UTC"},"created":"2013-12-09T16:40:05.892+0000","updated":"2013-12-09T16:40:05.892+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12483810/comment/13843321","id":"13843321","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=gtully","name":"gtully","key":"gtully","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Gary Tully","active":true,"timeZone":"Etc/UTC"},"body":"the change to the inTx flag is sorted in\nhttps://git-wip-us.apache.org/repos/asf?p=activemq.git;a=commit;h=b7c430d0","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=gtully","name":"gtully","key":"gtully","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Gary Tully","active":true,"timeZone":"Etc/UTC"},"created":"2013-12-09T17:04:31.281+0000","updated":"2013-12-09T17:04:31.281+0000"}],"maxResults":25,"total":25,"startAt":0},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/AMQ-1063/votes","votes":19,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i0am6v:"}}