{"expand":"renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations","id":"12407347","self":"https://issues.apache.org/jira/rest/api/2/issue/12407347","key":"HDFS-8","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype","name":"Bug","subtask":false,"avatarId":21133},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/12310942","id":"12310942","key":"HDFS","name":"Hadoop HDFS","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=12310942&avatarId=10094","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=12310942&avatarId=10094","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=12310942&avatarId=10094","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=12310942&avatarId=10094"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10292","id":"10292","description":"Scalable Distributed Computing","name":"Hadoop"}},"fixVersions":[],"aggregatetimespent":null,"resolution":{"self":"https://issues.apache.org/jira/rest/api/2/resolution/5","id":"5","description":"All attempts at reproducing this issue failed, or not enough information was available to reproduce the issue. Reading the code produces no clues as to why this behavior would occur. If more information appears later, please reopen the issue.","name":"Cannot Reproduce"},"customfield_12312322":null,"customfield_12310220":"2008-10-28T13:06:15.473+0000","customfield_12312520":null,"customfield_12312323":null,"customfield_12312521":"Tue Mar 25 13:02:28 UTC 2014","customfield_12310420":"16921","customfield_12312320":null,"customfield_12310222":"1_*:*_1_*:*_170553494777_*|*_5_*:*_1_*:*_0","customfield_12312321":null,"resolutiondate":"2014-03-25T13:02:28.471+0000","workratio":-1,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312923":null,"customfield_12312326":null,"customfield_12312920":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312921":null,"customfield_12312324":null,"customfield_12312720":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/HDFS-8/watchers","watchCount":2,"isWatching":false},"created":"2008-10-28T13:04:13.722+0000","customfield_12310192":null,"customfield_12310191":null,"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/4","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/minor.svg","name":"Minor","id":"4"},"labels":[],"customfield_12312333":null,"customfield_12310230":null,"customfield_12312334":null,"customfield_12313422":"false","customfield_12310310":"0.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"customfield_12311120":null,"customfield_12312330":null,"versions":[],"issuelinks":[],"customfield_12312339":null,"assignee":null,"customfield_12312337":null,"customfield_12312338":null,"updated":"2014-03-25T13:02:28.497+0000","customfield_12312335":null,"customfield_12312336":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/5","description":"A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/resolved.png","name":"Resolved","id":"5","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Done"}},"components":[],"timeoriginalestimate":null,"description":"My service setup/teardown tests are managing to trigger system exits in the namenode, which seems overkill.\n\n1. Interrupting the thread that is starting the namesystem up raises a java.nio.channels.ClosedByInterruptException.\n2. This is caught in FSImage.rollFSImage, and handed off to processIOError\n3. This triggers a call to Runtime.getRuntime().exit(-1); \"All storage directories are inaccessible.\".\n\nStack trace to follow. Exiting the JVM is somewhat overkill; if someone has interrupted the thread is is (presumably) because they want to stop the namenode, which may not imply they want to kill the JVM at the same time. Certainly JUnit does not expect it. \n\nSome possibilities\n -ClosedByInterruptException get handled differently as some form of shutdown request\n -Calls to system exit are factored out into something that can have its behaviour changed by policy options to throw a RuntimeException instead. \nHosting a Namenode in a security manager that blocks off System.exit() is the simplest workaround; this is fairly simple, but it means that what would be a straight exit does now get turned into an exception, so callers may be surprised by what happens.","customfield_10010":null,"timetracking":{},"customfield_12312026":null,"customfield_12312023":null,"customfield_12310320":null,"customfield_12312024":null,"customfield_12312340":null,"attachment":[],"aggregatetimeestimate":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12312022":null,"customfield_12310921":null,"customfield_12310920":"74404","customfield_12312823":null,"summary":"Interrupting the namenode thread triggers System.exit()","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=steve_l","name":"steve_l","key":"steve_l","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Steve Loughran","active":true,"timeZone":"Etc/UTC"},"subtasks":[],"customfield_12310291":null,"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=stevel%40apache.org","name":"stevel@apache.org","key":"stevel@apache.org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=stevel%40apache.org&avatarId=16513","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=stevel%40apache.org&avatarId=16513","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=stevel%40apache.org&avatarId=16513","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=stevel%40apache.org&avatarId=16513"},"displayName":"Steve Loughran","active":true,"timeZone":"Europe/London"},"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":0},"customfield_12311024":null,"environment":null,"customfield_12313520":null,"customfield_12311020":null,"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"comment":{"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12407347/comment/12643194","id":"12643194","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=steve_l","name":"steve_l","key":"steve_l","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Steve Loughran","active":true,"timeZone":"Etc/UTC"},"body":"stack trace. FSImage does not like to be interrupted.\n\n[sf-startdaemon-debug] 08/10/28 12:50:22 [Thread-305] ERROR common.Storage : Cannot write file /tmp/hadoop/dfs/name\n[sf-startdaemon-debug] java.nio.channels.ClosedByInterruptException\n[sf-startdaemon-debug]  at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:184)\n[sf-startdaemon-debug]  at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:271)\n[sf-startdaemon-debug]  at org.apache.hadoop.hdfs.server.common.Storage$StorageDirectory.write(Storage.java:268)\n[sf-startdaemon-debug]  at org.apache.hadoop.hdfs.server.common.Storage$StorageDirectory.write(Storage.java:244)\n[sf-startdaemon-debug]  at org.apache.hadoop.hdfs.server.namenode.FSImage.rollFSImage(FSImage.java:1316)\n[sf-startdaemon-debug]  at org.apache.hadoop.hdfs.server.namenode.FSImage.saveFSImage(FSImage.java:1034)\n[sf-startdaemon-debug]  at org.apache.hadoop.hdfs.server.namenode.FSDirectory.loadFSImage(FSDirectory.java:88)\n[sf-startdaemon-debug]  at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.initialize(FSNamesystem.java:311)\n[sf-startdaemon-debug]  at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.<init>(FSNamesystem.java:290)\n[sf-startdaemon-debug]  at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:165)\n[sf-startdaemon-debug]  at org.apache.hadoop.hdfs.server.namenode.NameNode.innerStart(NameNode.java:226)\n[sf-startdaemon-debug]  at org.apache.hadoop.util.Service.start(Service.java:188)\n[sf-startdaemon-debug]  at org.smartfrog.services.hadoop.components.cluster.HadoopServiceImpl.innerDeploy(HadoopServiceImpl.java:479)\n[sf-startdaemon-debug]  at org.smartfrog.services.hadoop.components.cluster.HadoopServiceImpl.access$000(HadoopServiceImpl.java:46)\n[sf-startdaemon-debug]  at org.smartfrog.services.hadoop.components.cluster.HadoopServiceImpl$ServiceDeployerThread.execute(HadoopServiceImpl.java:628)\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=steve_l","name":"steve_l","key":"steve_l","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Steve Loughran","active":true,"timeZone":"Etc/UTC"},"created":"2008-10-28T13:06:15.473+0000","updated":"2008-10-28T13:06:15.473+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12407347/comment/12643197","id":"12643197","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=steve_l","name":"steve_l","key":"steve_l","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Steve Loughran","active":true,"timeZone":"Etc/UTC"},"body":"This is very race condition dependent; a small change in machine timing and the interrupt is handled gracefully by reporting failure to the caller.\n\n[sf-startdaemon-debug] 08/10/28 13:15:07 [Thread-6] WARN util.Shell : Interrupted while reading the error stream\n[sf-startdaemon-debug] java.lang.InterruptedException\n[sf-startdaemon-debug]  at java.lang.Object.wait(Native Method)\n[sf-startdaemon-debug]  at java.lang.Thread.join(Thread.java:1143)\n[sf-startdaemon-debug]  at java.lang.Thread.join(Thread.java:1196)\n[sf-startdaemon-debug]  at org.apache.hadoop.util.Shell.runCommand(Shell.java:189)\n[sf-startdaemon-debug]  at org.apache.hadoop.util.Shell.run(Shell.java:134)\n[sf-startdaemon-debug]  at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:286)\n[sf-startdaemon-debug]  at org.apache.hadoop.util.Shell.execCommand(Shell.java:338)\n[sf-startdaemon-debug]  at org.apache.hadoop.security.UnixUserGroupInformation.executeShellCommand(UnixUserGroupInformation.java:326)\n[sf-startdaemon-debug]  at org.apache.hadoop.security.UnixUserGroupInformation.getUnixUserName(UnixUserGroupInformation.java:305)\n[sf-startdaemon-debug]  at org.apache.hadoop.security.UnixUserGroupInformation.login(UnixUserGroupInformation.java:232)\n[sf-startdaemon-debug]  at org.apache.hadoop.security.UnixUserGroupInformation.login(UnixUserGroupInformation.java:275)\n[sf-startdaemon-debug]  at org.apache.hadoop.security.UnixUserGroupInformation.login(UnixUserGroupInformation.java:257)\n[sf-startdaemon-debug]  at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.setConfigurationParameters(FSNamesystem.java:426)\n[sf-startdaemon-debug]  at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.initialize(FSNamesystem.java:304)\n[sf-startdaemon-debug]  at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.<init>(FSNamesystem.java:290)\n[sf-startdaemon-debug]  at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:165)\n[sf-startdaemon-debug]  at org.apache.hadoop.hdfs.server.namenode.NameNode.innerStart(NameNode.java:226)\n\ngiven I am interrupting threads during their initialization, I shouldn't expect things to work. But stopping the JVM is probably inappropriate.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=steve_l","name":"steve_l","key":"steve_l","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Steve Loughran","active":true,"timeZone":"Etc/UTC"},"created":"2008-10-28T13:19:10.981+0000","updated":"2008-10-28T13:19:10.981+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12407347/comment/12643246","id":"12643246","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=steve_l","name":"steve_l","key":"steve_l","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Steve Loughran","active":true,"timeZone":"Etc/UTC"},"body":"Intercepting System.exit() calls stops this and changes the stack to a transition to failed state instead.\nhttp://jira.smartfrog.org/jira/browse/SFOS-1016\n\n[sf-startdaemon-debug] 08/10/28 16:18:21 [Thread-305] INFO common.Storage : Image file of size 93 saved in 0 seconds.\n[sf-startdaemon-debug] 08/10/28 16:18:21 [Thread-305] ERROR namenode.FSNamesystem : FSNamesystem initialization failed.\n[sf-startdaemon-debug] java.nio.channels.ClosedByInterruptException\n[sf-startdaemon-debug]  at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:184)\n[sf-startdaemon-debug]  at sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:317)\n[sf-startdaemon-debug]  at org.apache.hadoop.hdfs.server.namenode.FSEditLog$EditLogFileOutputStream.<init>(FSEditLog.java:128)\n[sf-startdaemon-debug]  at org.apache.hadoop.hdfs.server.namenode.FSEditLog.createEditLogFile(FSEditLog.java:343)\n[sf-startdaemon-debug]  at org.apache.hadoop.hdfs.server.namenode.FSImage.saveFSImage(FSImage.java:1030)\n[sf-startdaemon-debug]  at org.apache.hadoop.hdfs.server.namenode.FSDirectory.loadFSImage(FSDirectory.java:88)\n[sf-startdaemon-debug]  at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.initialize(FSNamesystem.java:311)\n[sf-startdaemon-debug]  at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.<init>(FSNamesystem.java:290)\n[sf-startdaemon-debug]  at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:165)\n[sf-startdaemon-debug]  at org.apache.hadoop.hdfs.server.namenode.NameNode.innerStart(NameNode.java:226)\n[sf-startdaemon-debug]  at org.apache.hadoop.util.Service.start(Service.java:188)\n[sf-startdaemon-debug]  at org.smartfrog.services.hadoop.components.cluster.HadoopServiceImpl.innerDeploy(HadoopServiceImpl.java:479)\n[sf-startdaemon-debug]  at org.smartfrog.services.hadoop.components.cluster.HadoopServiceImpl.access$000(HadoopServiceImpl.java:46)\n[sf-startdaemon-debug]  at org.smartfrog.services.hadoop.components.cluster.HadoopServiceImpl$ServiceDeployerThread.execute(HadoopServiceImpl.java:628)\n[sf-startdaemon-debug]  at org.smartfrog.sfcore.utils.SmartFrogThread.run(SmartFrogThread.java:279)\n[sf-startdaemon-debug]  at org.smartfrog.sfcore.utils.WorkflowThread.run(WorkflowThread.java:117)\n[sf-startdaemon-debug] 08/10/28 16:18:21 [Thread-305] INFO namenode.NameNode : State change: NameNode is now FAILED\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=steve_l","name":"steve_l","key":"steve_l","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Steve Loughran","active":true,"timeZone":"Etc/UTC"},"created":"2008-10-28T16:32:34.914+0000","updated":"2008-10-28T16:32:34.914+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12407347/comment/12643361","id":"12643361","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=dhruba","name":"dhruba","key":"dhruba","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=dhruba&avatarId=30636","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=dhruba&avatarId=30636","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=dhruba&avatarId=30636","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=dhruba&avatarId=30636"},"displayName":"dhruba borthakur","active":true,"timeZone":"America/Tijuana"},"body":"> ClosedByInterruptException get handled differently as some form of shutdown request\n  This is closest to what we currently have in the NameNode.\n\n> Hosting a Namenode in a security manager that blocks off System.exit() \n  A Security Manager imposes additional performance overhead, doesn't it?","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=dhruba","name":"dhruba","key":"dhruba","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=dhruba&avatarId=30636","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=dhruba&avatarId=30636","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=dhruba&avatarId=30636","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=dhruba&avatarId=30636"},"displayName":"dhruba borthakur","active":true,"timeZone":"America/Tijuana"},"created":"2008-10-28T23:17:46.391+0000","updated":"2008-10-28T23:17:46.391+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12407347/comment/12643463","id":"12643463","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=steve_l","name":"steve_l","key":"steve_l","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Steve Loughran","active":true,"timeZone":"Etc/UTC"},"body":">> Hosting a Namenode in a security manager that blocks off System.exit()\n>A Security Manager imposes additional performance overhead, doesn't it?\n\nI've moved to the security manager hosting; it doesn't impose much of an overhead as only permissions for System.exit() are checked and intercepted. \n\nIt's still a bit odd killing the process if startup fails, however, as if you run <junit fork=\"true\"/> your process gets killed. In ant, <junit fork=\"false\" /> runs under a security manager purely to stop anyone calling System.exit() in their code.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=steve_l","name":"steve_l","key":"steve_l","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Steve Loughran","active":true,"timeZone":"Etc/UTC"},"created":"2008-10-29T10:54:17.744+0000","updated":"2008-10-29T10:54:17.744+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12407347/comment/13946475","id":"13946475","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=stevel%40apache.org","name":"stevel@apache.org","key":"stevel@apache.org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=stevel%40apache.org&avatarId=16513","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=stevel%40apache.org&avatarId=16513","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=stevel%40apache.org&avatarId=16513","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=stevel%40apache.org&avatarId=16513"},"displayName":"Steve Loughran","active":true,"timeZone":"Europe/London"},"body":"closing as so out of date it probably doesn't happen -and if it does, the stack trace is obsolete","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=stevel%40apache.org","name":"stevel@apache.org","key":"stevel@apache.org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=stevel%40apache.org&avatarId=16513","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=stevel%40apache.org&avatarId=16513","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=stevel%40apache.org&avatarId=16513","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=stevel%40apache.org&avatarId=16513"},"displayName":"Steve Loughran","active":true,"timeZone":"Europe/London"},"created":"2014-03-25T13:02:28.493+0000","updated":"2014-03-25T13:02:28.493+0000"}],"maxResults":6,"total":6,"startAt":0},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/HDFS-8/votes","votes":0,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i0d3vj:"}}