{"expand":"renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations","id":"12510976","self":"https://issues.apache.org/jira/rest/api/2/issue/12510976","key":"HDFS-2084","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype","name":"Bug","subtask":false,"avatarId":21133},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/12310942","id":"12310942","key":"HDFS","name":"Hadoop HDFS","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=12310942&avatarId=10094","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=12310942&avatarId=10094","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=12310942&avatarId=10094","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=12310942&avatarId=10094"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10292","id":"10292","description":"Scalable Distributed Computing","name":"Hadoop"}},"fixVersions":[],"aggregatetimespent":null,"resolution":{"self":"https://issues.apache.org/jira/rest/api/2/resolution/9","id":"9","description":"Unresolved","name":"Unresolved"},"customfield_12312322":null,"customfield_12310220":"2011-06-20T16:32:55.743+0000","customfield_12312520":null,"customfield_12312323":null,"customfield_12312521":"Sun Mar 01 08:07:04 UTC 2015","customfield_12310420":"126","customfield_12312320":null,"customfield_12310222":"10002_*:*_2_*:*_116610256325_*|*_1_*:*_2_*:*_71830_*|*_5_*:*_1_*:*_0","customfield_12312321":null,"resolutiondate":"2015-03-01T08:07:04.695+0000","workratio":-1,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312923":null,"customfield_12312326":null,"customfield_12312920":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312921":null,"customfield_12312324":null,"customfield_12312720":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/HDFS-2084/watchers","watchCount":4,"isWatching":false},"created":"2011-06-20T16:21:36.586+0000","customfield_12310192":null,"customfield_12310191":null,"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.svg","name":"Major","id":"3"},"labels":[],"customfield_12312333":null,"customfield_12310230":"workaround","customfield_12312334":null,"customfield_12313422":"false","customfield_12310310":"1.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"customfield_12311120":null,"customfield_12312330":null,"versions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12314046","id":"12314046","description":"","name":"0.21.0","archived":false,"released":true,"releaseDate":"2010-08-23"}],"issuelinks":[],"customfield_12312339":null,"assignee":null,"customfield_12312337":null,"customfield_12312338":null,"updated":"2015-03-01T08:07:04.737+0000","customfield_12312335":null,"customfield_12312336":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/5","description":"A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/resolved.png","name":"Resolved","id":"5","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Done"}},"components":[{"self":"https://issues.apache.org/jira/rest/api/2/component/12312926","id":"12312926","name":"namenode"}],"timeoriginalestimate":null,"description":"2011-06-17 11:43:23,096 ERROR org.apache.hadoop.hdfs.server.namenode.Checkpointer: Throwable Exception in doCheckpoint: \njava.lang.NullPointerException\n        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.unprotectedSetTimes(FSDirectory.java:1765)\n        at org.apache.hadoop.hdfs.server.namenode.FSDirectory.unprotectedSetTimes(FSDirectory.java:1753)\n        at org.apache.hadoop.hdfs.server.namenode.FSEditLog.loadEditRecords(FSEditLog.java:708)\n        at org.apache.hadoop.hdfs.server.namenode.FSEditLog.loadFSEdits(FSEditLog.java:411)\n        at org.apache.hadoop.hdfs.server.namenode.FSEditLog.loadFSEdits(FSEditLog.java:378)\n        at org.apache.hadoop.hdfs.server.namenode.FSImage.loadFSEdits(FSImage.java:1209)\n        at org.apache.hadoop.hdfs.server.namenode.BackupStorage.loadCheckpoint(BackupStorage.java:158)\n        at org.apache.hadoop.hdfs.server.namenode.Checkpointer.doCheckpoint(Checkpointer.java:243)\n        at org.apache.hadoop.hdfs.server.namenode.Checkpointer.run(Checkpointer.java:141)\n","customfield_10010":null,"timetracking":{},"customfield_12312026":null,"customfield_12312023":null,"customfield_12310320":null,"customfield_12312024":null,"customfield_12312340":null,"attachment":[{"self":"https://issues.apache.org/jira/rest/api/2/attachment/12483166","id":"12483166","filename":"patch.diff","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=tivv","name":"tivv","key":"tivv","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=tivv&avatarId=16734","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=tivv&avatarId=16734","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=tivv&avatarId=16734","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=tivv&avatarId=16734"},"displayName":"Vitalii Tymchyshyn","active":true,"timeZone":"America/New_York"},"created":"2011-06-20T16:24:32.797+0000","size":1043,"mimeType":"text/x-patch","content":"https://issues.apache.org/jira/secure/attachment/12483166/patch.diff"}],"aggregatetimeestimate":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12312022":null,"customfield_12310921":null,"customfield_12310920":"113768","customfield_12312823":null,"summary":"Sometimes backup node/secondary name node stops with exception","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=tivv","name":"tivv","key":"tivv","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=tivv&avatarId=16734","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=tivv&avatarId=16734","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=tivv&avatarId=16734","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=tivv&avatarId=16734"},"displayName":"Vitalii Tymchyshyn","active":true,"timeZone":"America/New_York"},"subtasks":[],"customfield_12310291":null,"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=tivv","name":"tivv","key":"tivv","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=tivv&avatarId=16734","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=tivv&avatarId=16734","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=tivv&avatarId=16734","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=tivv&avatarId=16734"},"displayName":"Vitalii Tymchyshyn","active":true,"timeZone":"America/New_York"},"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":0},"customfield_12311024":null,"environment":"FreeBSD","customfield_12313520":null,"customfield_12311020":null,"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"comment":{"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12510976/comment/13052037","id":"13052037","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=tivv","name":"tivv","key":"tivv","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=tivv&avatarId=16734","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=tivv&avatarId=16734","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=tivv&avatarId=16734","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=tivv&avatarId=16734"},"displayName":"Vitalii Tymchyshyn","active":true,"timeZone":"America/New_York"},"body":"This is my patch to skip such problematic entries","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=tivv","name":"tivv","key":"tivv","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=tivv&avatarId=16734","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=tivv&avatarId=16734","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=tivv&avatarId=16734","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=tivv&avatarId=16734"},"displayName":"Vitalii Tymchyshyn","active":true,"timeZone":"America/New_York"},"created":"2011-06-20T16:22:39.701+0000","updated":"2011-06-20T16:22:39.701+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12510976/comment/13052039","id":"13052039","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=tivv","name":"tivv","key":"tivv","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=tivv&avatarId=16734","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=tivv&avatarId=16734","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=tivv&avatarId=16734","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=tivv&avatarId=16734"},"displayName":"Vitalii Tymchyshyn","active":true,"timeZone":"America/New_York"},"body":"This is patch to skip such entries. Note that it's against my \"own copy\" of 0.21 release tag, so revisions are from my svn","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=tivv","name":"tivv","key":"tivv","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=tivv&avatarId=16734","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=tivv&avatarId=16734","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=tivv&avatarId=16734","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=tivv&avatarId=16734"},"displayName":"Vitalii Tymchyshyn","active":true,"timeZone":"America/New_York"},"created":"2011-06-20T16:24:32.847+0000","updated":"2011-06-20T16:24:32.847+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12510976/comment/13052048","id":"13052048","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hadoopqa","name":"hadoopqa","key":"hadoopqa","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=hadoopqa&avatarId=10393","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hadoopqa&avatarId=10393","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=hadoopqa&avatarId=10393","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=hadoopqa&avatarId=10393"},"displayName":"Hadoop QA","active":true,"timeZone":"Etc/UTC"},"body":"-1 overall.  Here are the results of testing the latest attachment \n  http://issues.apache.org/jira/secure/attachment/12483166/patch.diff\n  against trunk revision 1137675.\n\n    +1 @author.  The patch does not contain any @author tags.\n\n    -1 tests included.  The patch doesn't appear to include any new or modified tests.\n                        Please justify why no new tests are needed for this patch.\n                        Also please list what manual steps were performed to verify this patch.\n\n    -1 patch.  The patch command could not apply the patch.\n\nConsole output: https://builds.apache.org/job/PreCommit-HDFS-Build/799//console\n\nThis message is automatically generated.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hadoopqa","name":"hadoopqa","key":"hadoopqa","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=hadoopqa&avatarId=10393","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hadoopqa&avatarId=10393","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=hadoopqa&avatarId=10393","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=hadoopqa&avatarId=10393"},"displayName":"Hadoop QA","active":true,"timeZone":"Etc/UTC"},"created":"2011-06-20T16:32:55.743+0000","updated":"2011-06-20T16:32:55.743+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12510976/comment/13052248","id":"13052248","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=shv","name":"shv","key":"shv","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Konstantin Shvachko","active":true,"timeZone":"America/Los_Angeles"},"body":"Looks like the checkpoint contains a record which tries to set time on a non-existing file. This should not happen. So the question is how did it happen? If it's a bug we should fix the cause. I don't see how, but if it's a legal scenario, then we can suppress NPE as you suggest.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=shv","name":"shv","key":"shv","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Konstantin Shvachko","active":true,"timeZone":"America/Los_Angeles"},"created":"2011-06-20T22:21:33.603+0000","updated":"2011-06-20T22:21:33.603+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12510976/comment/13052360","id":"13052360","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=tivv","name":"tivv","key":"tivv","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=tivv&avatarId=16734","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=tivv&avatarId=16734","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=tivv&avatarId=16734","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=tivv&avatarId=16734"},"displayName":"Vitalii Tymchyshyn","active":true,"timeZone":"America/New_York"},"body":"I dont know how does it happen, but it does often for me. I have a copy of namenode state that produces this problem on start I can share.\nIn general, as for me, it would be great to have an option to perform a checkpoint skipping invalid records of any kind. Because now any such record make namenode unusable on restart and with an option you will at most loose a bit of information.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=tivv","name":"tivv","key":"tivv","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=tivv&avatarId=16734","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=tivv&avatarId=16734","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=tivv&avatarId=16734","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=tivv&avatarId=16734"},"displayName":"Vitalii Tymchyshyn","active":true,"timeZone":"America/New_York"},"created":"2011-06-21T06:24:10.571+0000","updated":"2011-06-21T06:24:10.571+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12510976/comment/13052635","id":"13052635","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=tivv","name":"tivv","key":"tivv","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=tivv&avatarId=16734","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=tivv&avatarId=16734","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=tivv&avatarId=16734","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=tivv&avatarId=16734"},"displayName":"Vitalii Tymchyshyn","active":true,"timeZone":"America/New_York"},"body":"Some more details:\nI am working on jobs, each produce multiple tasks. ZooKeeper is used to spread tasks over the computing cluster. \nTasks inside single job communicate (produce result files that are used on start by another tasks) with HDFS.\nThe job has main control process. Before the job starts it creates directory to put communication files into and original job arguments.\nAfter job is finished, it removes the directory with single call.\nThe problem was reproduced today with a number of communication files of a single job.\nNote that while job is deleted when all the tasks is done, there may be some \"hanging\" tasks that did timeouted and was restarted. In this case, unhang may lead to access try to file that do not exists. \nI will try to check with logs if this was the case.\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=tivv","name":"tivv","key":"tivv","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=tivv&avatarId=16734","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=tivv&avatarId=16734","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=tivv&avatarId=16734","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=tivv&avatarId=16734"},"displayName":"Vitalii Tymchyshyn","active":true,"timeZone":"America/New_York"},"created":"2011-06-21T16:02:36.043+0000","updated":"2011-06-21T16:02:36.043+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12510976/comment/13052640","id":"13052640","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=tivv","name":"tivv","key":"tivv","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=tivv&avatarId=16734","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=tivv&avatarId=16734","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=tivv&avatarId=16734","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=tivv&avatarId=16734"},"displayName":"Vitalii Tymchyshyn","active":true,"timeZone":"America/New_York"},"body":"I did check the job and could find nothing special. The files existed a little less then hour before the job was deleted. Nothing regarding file names in name node log.\nUnfortunatelly I did not output the times being applied to the log, so I can't check if it's inside or outside (or on the edge of) the interval where files were existing.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=tivv","name":"tivv","key":"tivv","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=tivv&avatarId=16734","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=tivv&avatarId=16734","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=tivv&avatarId=16734","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=tivv&avatarId=16734"},"displayName":"Vitalii Tymchyshyn","active":true,"timeZone":"America/New_York"},"created":"2011-06-21T16:15:28.725+0000","updated":"2011-06-21T16:15:28.725+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12510976/comment/14310249","id":"14310249","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hadoopqa","name":"hadoopqa","key":"hadoopqa","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=hadoopqa&avatarId=10393","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hadoopqa&avatarId=10393","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=hadoopqa&avatarId=10393","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=hadoopqa&avatarId=10393"},"displayName":"Hadoop QA","active":true,"timeZone":"Etc/UTC"},"body":"{color:red}-1 overall{color}.  Here are the results of testing the latest attachment \n  http://issues.apache.org/jira/secure/attachment/12483166/patch.diff\n  against trunk revision da2fb2b.\n\n    {color:red}-1 patch{color}.  The patch command could not apply the patch.\n\nConsole output: https://builds.apache.org/job/PreCommit-HDFS-Build/9475//console\n\nThis message is automatically generated.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hadoopqa","name":"hadoopqa","key":"hadoopqa","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=hadoopqa&avatarId=10393","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hadoopqa&avatarId=10393","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=hadoopqa&avatarId=10393","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=hadoopqa&avatarId=10393"},"displayName":"Hadoop QA","active":true,"timeZone":"Etc/UTC"},"created":"2015-02-07T00:07:20.172+0000","updated":"2015-02-07T00:07:20.172+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12510976/comment/14342047","id":"14342047","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=aw","name":"aw","key":"aw","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=aw&avatarId=23681","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=aw&avatarId=23681","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=aw&avatarId=23681","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=aw&avatarId=23681"},"displayName":"Allen Wittenauer","active":true,"timeZone":"America/Tijuana"},"body":"Cancelling this issue as stale since the patch no longer applies and given the number of changes to the NN in the past four years, there is a good chance the issue has been dealt with. If not, please re-open. \n\nThanks.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=aw","name":"aw","key":"aw","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=aw&avatarId=23681","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=aw&avatarId=23681","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=aw&avatarId=23681","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=aw&avatarId=23681"},"displayName":"Allen Wittenauer","active":true,"timeZone":"America/Tijuana"},"created":"2015-03-01T08:07:04.729+0000","updated":"2015-03-01T08:07:04.729+0000"}],"maxResults":9,"total":9,"startAt":0},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/HDFS-2084/votes","votes":0,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i0jtv3:"}}