{"expand":"renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations","id":"12769109","self":"https://issues.apache.org/jira/rest/api/2/issue/12769109","key":"HIVE-9436","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype","name":"Bug","subtask":false,"avatarId":21133},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/12310843","id":"12310843","key":"HIVE","name":"Hive","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=12310843&avatarId=11935","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=12310843&avatarId=11935","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=12310843&avatarId=11935","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=12310843&avatarId=11935"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10292","id":"10292","description":"Scalable Distributed Computing","name":"Hadoop"}},"fixVersions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12329278","id":"12329278","description":"Branch 1.0 release","name":"1.0.0","archived":false,"released":true,"releaseDate":"2015-02-04"}],"aggregatetimespent":null,"resolution":{"self":"https://issues.apache.org/jira/rest/api/2/resolution/1","id":"1","description":"A fix for this issue is checked into the tree and tested.","name":"Fixed"},"customfield_12312322":null,"customfield_12310220":"2015-01-21T22:52:44.923+0000","customfield_12312520":null,"customfield_12312323":null,"customfield_12312521":"Thu Feb 19 18:21:53 UTC 2015","customfield_12310420":"9223372036854775807","customfield_12312320":null,"customfield_12310222":"10002_*:*_3_*:*_605025536_*|*_1_*:*_3_*:*_9951560_*|*_5_*:*_1_*:*_0","customfield_12312321":null,"resolutiondate":"2015-01-28T23:58:48.976+0000","workratio":-1,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312923":null,"customfield_12312326":null,"customfield_12312920":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312921":null,"customfield_12312324":null,"customfield_12312720":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/HIVE-9436/watchers","watchCount":4,"isWatching":false},"created":"2015-01-21T21:09:11.929+0000","customfield_12310192":null,"customfield_12310191":null,"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.svg","name":"Major","id":"3"},"labels":[],"customfield_12312333":null,"customfield_12310230":null,"customfield_12312334":null,"customfield_12313422":"false","customfield_12310310":"3.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"customfield_12311120":null,"customfield_12312330":null,"versions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12326450","id":"12326450","description":"released","name":"0.14.0","archived":false,"released":true,"releaseDate":"2014-11-12"},{"self":"https://issues.apache.org/jira/rest/api/2/version/12326829","id":"12326829","description":"0.13 maintenance release 1","name":"0.13.1","archived":false,"released":true,"releaseDate":"2014-06-06"}],"issuelinks":[{"id":"12490360","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12490360","type":{"id":"10030","name":"Reference","inward":"is related to","outward":"relates to","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/10030"},"outwardIssue":{"id":"12822008","key":"HIVE-10384","self":"https://issues.apache.org/jira/rest/api/2/issue/12822008","fields":{"summary":"RetryingMetaStoreClient does not retry wrapped TTransportExceptions","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are not closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Done"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.svg","name":"Major","id":"3"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype","name":"Bug","subtask":false,"avatarId":21133}}}}],"customfield_12312339":null,"assignee":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"customfield_12312337":null,"customfield_12312338":null,"updated":"2017-01-05T18:02:22.494+0000","customfield_12312335":null,"customfield_12312336":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are not closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Done"}},"components":[],"timeoriginalestimate":null,"description":"RetryingMetaStoreClient has a bug in the following bit of code:\n\n{code}\n        } else if ((e.getCause() instanceof MetaException) &&\n            e.getCause().getMessage().matches(\"JDO[a-zA-Z]*Exception\")) {\n          caughtException = (MetaException) e.getCause();\n        } else {\n          throw e.getCause();\n        }\n{code}\n\n\nThe bug here is that java String.matches matches the entire string to the regex, and thus, that match will fail if the message contains anything before or after JDO[a-zA-Z]\\*Exception. The solution, however, is very simple, we should match (?s).\\*JDO[a-zA-Z]\\*Exception.\\*","customfield_10010":null,"timetracking":{},"customfield_12312026":null,"customfield_12312023":null,"customfield_12310320":null,"customfield_12312024":null,"customfield_12312340":null,"attachment":[{"self":"https://issues.apache.org/jira/rest/api/2/attachment/12694069","id":"12694069","filename":"HIVE-9436.2.patch","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-01-23T02:20:59.281+0000","size":927,"mimeType":"text/plain","content":"https://issues.apache.org/jira/secure/attachment/12694069/HIVE-9436.2.patch"},{"self":"https://issues.apache.org/jira/rest/api/2/attachment/12694681","id":"12694681","filename":"HIVE-9436.3.patch","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-01-27T01:53:00.253+0000","size":927,"mimeType":"text/plain","content":"https://issues.apache.org/jira/secure/attachment/12694681/HIVE-9436.3.patch"},{"self":"https://issues.apache.org/jira/rest/api/2/attachment/12693708","id":"12693708","filename":"HIVE-9436.patch","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-01-21T21:12:38.652+0000","size":923,"mimeType":"text/plain","content":"https://issues.apache.org/jira/secure/attachment/12693708/HIVE-9436.patch"}],"aggregatetimeestimate":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12312022":null,"customfield_12310921":null,"customfield_12310920":"9223372036854775807","customfield_12312823":null,"summary":"RetryingMetaStoreClient does not retry JDOExceptions","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"subtasks":[],"customfield_12310291":null,"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":0},"customfield_12311024":null,"environment":null,"customfield_12313520":null,"customfield_12311020":null,"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"comment":{"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12769109/comment/14286281","id":"14286281","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"body":"Attaching patch. [~thejas], could you please review?","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-01-21T21:12:38.731+0000","updated":"2015-01-21T21:12:38.731+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12769109/comment/14286475","id":"14286475","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=thejas","name":"thejas","key":"thejas","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=thejas&avatarId=15902","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=thejas&avatarId=15902","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=thejas&avatarId=15902","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=thejas&avatarId=15902"},"displayName":"Thejas M Nair","active":true,"timeZone":"America/Los_Angeles"},"body":"+1","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=thejas","name":"thejas","key":"thejas","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=thejas&avatarId=15902","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=thejas&avatarId=15902","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=thejas&avatarId=15902","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=thejas&avatarId=15902"},"displayName":"Thejas M Nair","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-01-21T22:52:44.923+0000","updated":"2015-01-21T22:52:44.923+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12769109/comment/14286974","id":"14286974","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hiveqa","name":"hiveqa","key":"hiveqa","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=hiveqa&avatarId=17060","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hiveqa&avatarId=17060","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=hiveqa&avatarId=17060","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=hiveqa&avatarId=17060"},"displayName":"Hive QA","active":true,"timeZone":"America/Chicago"},"body":"\n\n{color:red}Overall{color}: -1 at least one tests failed\n\nHere are the results of testing the latest attachment:\nhttps://issues.apache.org/jira/secure/attachment/12693708/HIVE-9436.patch\n\n{color:red}ERROR:{color} -1 due to 1 failed/errored test(s), 7347 tests executed\n*Failed tests:*\n{noformat}\norg.apache.hadoop.hive.cli.TestMinimrCliDriver.testCliDriver_schemeAuthority\n{noformat}\n\nTest results: http://ec2-174-129-184-35.compute-1.amazonaws.com/jenkins/job/PreCommit-HIVE-TRUNK-Build/2470/testReport\nConsole output: http://ec2-174-129-184-35.compute-1.amazonaws.com/jenkins/job/PreCommit-HIVE-TRUNK-Build/2470/console\nTest logs: http://ec2-174-129-184-35.compute-1.amazonaws.com/logs/PreCommit-HIVE-TRUNK-Build-2470/\n\nMessages:\n{noformat}\nExecuting org.apache.hive.ptest.execution.PrepPhase\nExecuting org.apache.hive.ptest.execution.ExecutionPhase\nExecuting org.apache.hive.ptest.execution.ReportingPhase\nTests exited with: TestsFailedException: 1 tests failed\n{noformat}\n\nThis message is automatically generated.\n\nATTACHMENT ID: 12693708 - PreCommit-HIVE-TRUNK-Build","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hiveqa","name":"hiveqa","key":"hiveqa","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=hiveqa&avatarId=17060","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hiveqa&avatarId=17060","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=hiveqa&avatarId=17060","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=hiveqa&avatarId=17060"},"displayName":"Hive QA","active":true,"timeZone":"America/Chicago"},"created":"2015-01-22T05:24:46.099+0000","updated":"2015-01-22T05:24:46.099+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12769109/comment/14288461","id":"14288461","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"body":"Canceling patch to update one more thing - this needs to be a multiline match, from the looks of it.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-01-22T23:39:45.467+0000","updated":"2015-01-22T23:39:45.467+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12769109/comment/14288534","id":"14288534","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hsubramaniyan","name":"hsubramaniyan","key":"hsubramaniyan","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=hsubramaniyan&avatarId=23453","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hsubramaniyan&avatarId=23453","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=hsubramaniyan&avatarId=23453","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=hsubramaniyan&avatarId=23453"},"displayName":"Hari Sankar Sivarama Subramaniyan","active":true,"timeZone":"America/Los_Angeles"},"body":"A minor comment since I remember looking at RetryingHMSHandler code for  catching Nucleus Exceptions a while back. I think RetryingHMSHandler::invoke and RetryingMetaStoreClient::invoke should have similar  exceptions caught(except might be TException or something that might be client specific or HMS handler specific). Is it possible to factorize the catch part and have them called from  RetryingMetaStoreClient::invoke and RetryingHMSHandler::invoke to avoid any redundancy/ missing cases. If this is not possible, manually comparing these two functions for the exception type handled might help in resolving any similar missing exception handling cases. Another point is comparing the exception messages for JDOException regex  looks a bit hairy to me. Please correct me if this understanding is wrong.\n\nThanks\nHari","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hsubramaniyan","name":"hsubramaniyan","key":"hsubramaniyan","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=hsubramaniyan&avatarId=23453","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hsubramaniyan&avatarId=23453","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=hsubramaniyan&avatarId=23453","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=hsubramaniyan&avatarId=23453"},"displayName":"Hari Sankar Sivarama Subramaniyan","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-01-23T01:16:21.648+0000","updated":"2015-01-23T01:16:21.648+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12769109/comment/14288611","id":"14288611","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"body":"Updated patch to multi-line match","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-01-23T02:20:59.290+0000","updated":"2015-01-23T02:20:59.290+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12769109/comment/14288623","id":"14288623","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"body":"Hari, good point - I had a look at RetryingHMSHandler, and the code is rather similar. There seems to be two main differences though: First, on the HMSHandler side, the exact cause-chain of exceptions are still available, and we can compare using \"instanceof\", whereas on the client-side, we have only the first level exception object, and all internal objects are serialized, so we have to look at the messages instead. Secondly, the client has thrift-related exceptions which are acceptable as well.\n\nStill, possibly, we should undertake to refactor this into MetastoreUtils with a parameter which asks whether to look strictly at types, or look inside the messages as well, and call that from both sides, and also pass in a list of acceptable exception types. In that scenario, this would be usable all over the place where we need to retry. I would, however, like to tackle the refactor as an improvement rather than in a bug-fix jira if that's okay.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-01-23T02:27:27.948+0000","updated":"2015-01-23T02:27:27.948+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12769109/comment/14288800","id":"14288800","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=thejas","name":"thejas","key":"thejas","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=thejas&avatarId=15902","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=thejas&avatarId=15902","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=thejas&avatarId=15902","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=thejas&avatarId=15902"},"displayName":"Thejas M Nair","active":true,"timeZone":"America/Los_Angeles"},"body":"[~hsubramaniyan] that is a good point regarding the two places where exception checks and retries are happening. IMO, the metastore client should ideally only retry any issue related to communication with metastore server. HMSHandler is the one that should retry on any temporary errors such as JDOException. As [~sushanth] said we have the real cause available there and we can do an instanceof check over there. It seems like a simple and cleaner change to do the check there. [~sushanth] What do you think ?\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=thejas","name":"thejas","key":"thejas","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=thejas&avatarId=15902","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=thejas&avatarId=15902","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=thejas&avatarId=15902","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=thejas&avatarId=15902"},"displayName":"Thejas M Nair","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-01-23T05:50:33.850+0000","updated":"2015-01-23T05:50:33.850+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12769109/comment/14289628","id":"14289628","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hiveqa","name":"hiveqa","key":"hiveqa","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=hiveqa&avatarId=17060","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hiveqa&avatarId=17060","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=hiveqa&avatarId=17060","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=hiveqa&avatarId=17060"},"displayName":"Hive QA","active":true,"timeZone":"America/Chicago"},"body":"\n\n{color:red}Overall{color}: -1 at least one tests failed\n\nHere are the results of testing the latest attachment:\nhttps://issues.apache.org/jira/secure/attachment/12694069/HIVE-9436.2.patch\n\n{color:red}ERROR:{color} -1 due to 67 failed/errored test(s), 7346 tests executed\n*Failed tests:*\n{noformat}\nTestCustomAuthentication - did not produce a TEST-*.xml file\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_archive_excludeHadoop20\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_archive_multi\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_auto_join11\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_auto_join12\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_auto_join13\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_auto_join27\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_auto_join4\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_auto_join5\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_auto_join8\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_cbo_simple_select\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_cbo_subq_in\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_column_access_stats\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_constantPropagateForSubQuery\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_correlationoptimizer1\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_correlationoptimizer6\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_correlationoptimizer8\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_explain_logical\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_filter_join_breaktask\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_filter_join_breaktask2\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_groupby_sort_1_23\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_groupby_sort_skew_1_23\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_metadataOnlyOptimizer\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_metadataonly1\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_ppd_gby2\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_ppd_join_filter\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_ppd_outer_join5\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_ppd_union_view\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_ppd_vc\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_rcfile_union\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_smb_mapjoin_25\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_subquery_in\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_subquery_in_having\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_subquery_notin\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_subquery_notin_having\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_subquery_views\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_table_access_keys_stats\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_udaf_histogram_numeric\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_union24\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_union28\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_union30\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_union_null\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_union_remove_10\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_union_remove_2\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_union_remove_5\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_union_remove_6_subq\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_union_remove_8\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_union_remove_9\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_vector_decimal_mapjoin\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_vector_mapjoin_reduce\norg.apache.hadoop.hive.cli.TestMiniTezCliDriver.testCliDriver_cbo_simple_select\norg.apache.hadoop.hive.cli.TestMiniTezCliDriver.testCliDriver_cbo_subq_in\norg.apache.hadoop.hive.cli.TestMiniTezCliDriver.testCliDriver_dynamic_partition_pruning\norg.apache.hadoop.hive.cli.TestMiniTezCliDriver.testCliDriver_dynamic_partition_pruning_2\norg.apache.hadoop.hive.cli.TestMiniTezCliDriver.testCliDriver_filter_join_breaktask\norg.apache.hadoop.hive.cli.TestMiniTezCliDriver.testCliDriver_filter_join_breaktask2\norg.apache.hadoop.hive.cli.TestMiniTezCliDriver.testCliDriver_mrr\norg.apache.hadoop.hive.cli.TestMiniTezCliDriver.testCliDriver_subquery_in\norg.apache.hadoop.hive.cli.TestMiniTezCliDriver.testCliDriver_vector_decimal_mapjoin\norg.apache.hadoop.hive.cli.TestMiniTezCliDriver.testCliDriver_vector_mapjoin_reduce\norg.apache.hadoop.hive.cli.TestMiniTezCliDriver.testCliDriver_vectorized_dynamic_partition_pruning\norg.apache.hadoop.hive.cli.TestMinimrCliDriver.testCliDriver_constprog_partitioner\norg.apache.hadoop.hive.cli.TestMinimrCliDriver.testCliDriver_ql_rewrite_gbtoidx_cbo_1\norg.apache.hadoop.hive.cli.TestMinimrCliDriver.testCliDriver_ql_rewrite_gbtoidx_cbo_2\norg.apache.hadoop.hive.thrift.TestHadoop20SAuthBridge.testMetastoreProxyUser\norg.apache.hadoop.hive.thrift.TestHadoop20SAuthBridge.testSaslWithHiveMetaStore\norg.apache.hive.hcatalog.streaming.TestStreaming.testEndpointConnection\n{noformat}\n\nTest results: http://ec2-174-129-184-35.compute-1.amazonaws.com/jenkins/job/PreCommit-HIVE-TRUNK-Build/2495/testReport\nConsole output: http://ec2-174-129-184-35.compute-1.amazonaws.com/jenkins/job/PreCommit-HIVE-TRUNK-Build/2495/console\nTest logs: http://ec2-174-129-184-35.compute-1.amazonaws.com/logs/PreCommit-HIVE-TRUNK-Build-2495/\n\nMessages:\n{noformat}\nExecuting org.apache.hive.ptest.execution.PrepPhase\nExecuting org.apache.hive.ptest.execution.ExecutionPhase\nExecuting org.apache.hive.ptest.execution.ReportingPhase\nTests exited with: TestsFailedException: 67 tests failed\n{noformat}\n\nThis message is automatically generated.\n\nATTACHMENT ID: 12694069 - PreCommit-HIVE-TRUNK-Build","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hiveqa","name":"hiveqa","key":"hiveqa","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=hiveqa&avatarId=17060","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hiveqa&avatarId=17060","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=hiveqa&avatarId=17060","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=hiveqa&avatarId=17060"},"displayName":"Hive QA","active":true,"timeZone":"America/Chicago"},"created":"2015-01-23T18:06:17.511+0000","updated":"2015-01-23T18:06:17.511+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12769109/comment/14289829","id":"14289829","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"body":"Randomly sampling some of the test failures:\n\n{noformat}\nsource/itests/qtest/../../itests/qtest/target/qfile-results/clientpositive/udaf_histogram_numeric.q.out /home/hiveptest/54.205.215.38-hiveptest-1/apache-svn-trunk-source/itests/qtest/../../ql/src/test/results/clientpositive/udaf_histogram_numeric.q.out\n9c9\n< [{\"x\":139.16078431372554,\"y\":255.0},{\"x\":386.1428571428572,\"y\":245.0}]\n---\n> [{\"x\":135.0284552845532,\"y\":246.0},{\"x\":381.39370078740143,\"y\":254.0}]\n{noformat}\n\n{noformat}\nRunning: diff -a /home/hiveptest/54.159.206.72-hiveptest-1/apache-svn-trunk-source/itests/qtest/../../itests/qtest/target/qfile-results/clientpositive/auto_join12.q.out /home/hiveptest/54.159.206.72-hiveptest-1/apache-svn-trunk-source/itests/qtest/../../ql/src/test/results/clientpositive/auto_join12.q.out\n32c32\n<         $hdt$_0:$hdt$_0:$hdt$_0:$hdt$_0:src \n---\n>         $hdt$_0:$hdt$_0:$hdt$_0:$hdt$_0:$hdt$_0:src \n35c35\n<         $hdt$_0:$hdt$_0:$hdt$_1:$hdt$_1:$hdt$_1:src \n---\n>         $hdt$_0:$hdt$_0:$hdt$_1:$hdt$_1:$hdt$_1:$hdt$_1:src \n39c39\n<         $hdt$_0:$hdt$_0:$hdt$_0:$hdt$_0:src \n---\n>         $hdt$_0:$hdt$_0:$hdt$_0:$hdt$_0:$hdt$_0:src \n54c54\n<         $hdt$_0:$hdt$_0:$hdt$_1:$hdt$_1:$hdt$_1:src \n---\n>         $hdt$_0:$hdt$_0:$hdt$_1:$hdt$_1:$hdt$_1:$hdt$_1:src \n{noformat}\n\nNeither of those have anything whatsoever to do with retries.\n\nAlso, I see some other errors reporting \"junit.framework.AssertionFailedError: Client Execution failed with error code = 40000 running\", which is similar to what's reported in HIVE-8997. Is there a test flakiness issue right now in trunk?","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-01-23T19:51:41.885+0000","updated":"2015-01-23T19:51:41.885+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12769109/comment/14289961","id":"14289961","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"body":"[~thejas]/[~hsubramaniyan] : I have a couple of thoughts about moving JDOException retries solely to the metastore:\n\na) Firstly, we have had cases so far where a JDOException invalidates the connection on the metastore side, and retrying from the metastore has not helped. Retrying from the client-side, though, causes a fresh openTransaction() that clears the connection and all history, sometimes by hitting a different HMSHandler, and this causes the retry from client to be more successful than a retry from server. Admittedly, this is more likely because we need to clean up our metastore code to make sure that the retry from the metastore-side handles this properly, and thus, is something we should attempt to improve.\nb) Second, from a perspective of a loaded metastore, having a metastore thread do retries, thus using up valuable metastore resources/time is more wasteful than having the client do retries. We thus tend to keep our metastore-side retries to a low amount, but the fact that we have client-side retries as well gives us an ability to be fail-fast on the metastore, but retry a large number of times in particular clients if we find the need to do so. Particularly, in HA configurations, I've seen a large number of retries and longer retry-intervals on the client side that allow a connection to go through despite metastore HUPs.\nc) Thirdly, speaking of HA, retrying on the client-side allows us to hit alternate metastores as well, if configured, if we have scenarios where one metastore is getting bogged down. As you mention, client should ideally only be retrying connection exceptions, but JDOExceptions are frequently the result of connection exceptions raised by the connection pool from the metastore to the db.\n\nThere is definitely scope for refactoring and improvement in all this, I will look into it further, but for now, this is a simpler bugfix to enable the already-existing regex to work correctly.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-01-23T20:58:07.695+0000","updated":"2015-01-23T20:58:07.695+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12769109/comment/14289984","id":"14289984","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"body":"As to the precommit tests, it looks like the majority of those tests were already failing before this build:\n\n{noformat}\nTest Result (66 failures / +3)\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_udaf_histogram_numeric\norg.apache.hadoop.hive.thrift.TestHadoop20SAuthBridge.testSaslWithHiveMetaStore\norg.apache.hadoop.hive.thrift.TestHadoop20SAuthBridge.testMetastoreProxyUser\norg.apache.hive.hcatalog.streaming.TestStreaming.testEndpointConnection\n...\n{noformat}\n\nThis indicates that tests were already flaky (probably due to an earlier commit?) and there were a total of 3 reported regressions. Diffing between this build(2495) and the previous one where tests ran (2493) to find changes, I get:\n\n{noformat}\n< org.apache.hadoop.hive.cli.TestMinimrCliDriver.testCliDriver_bucket5\n---\n> org.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_udaf_histogram_numeric\n> org.apache.hadoop.hive.thrift.TestHadoop20SAuthBridge.testSaslWithHiveMetaStore\n> org.apache.hadoop.hive.thrift.TestHadoop20SAuthBridge.testMetastoreProxyUser\n> org.apache.hive.hcatalog.streaming.TestStreaming.testEndpointConnection\n{noformat}\n\nFor org.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_udaf_histogram_numeric:\n\n{noformat}\nRunning: diff -a /home/hiveptest/54.205.215.38-hiveptest-1/apache-svn-trunk-source/itests/qtest/../../itests/qtest/target/qfile-results/clientpositive/udaf_histogram_numeric.q.out /home/hiveptest/54.205.215.38-hiveptest-1/apache-svn-trunk-source/itests/qtest/../../ql/src/test/results/clientpositive/udaf_histogram_numeric.q.out\n9c9\n< [{\"x\":139.16078431372554,\"y\":255.0},{\"x\":386.1428571428572,\"y\":245.0}]\n---\n> [{\"x\":135.0284552845532,\"y\":246.0},{\"x\":381.39370078740143,\"y\":254.0}]\n{noformat}\n\nThis does not look connected to this issue.\n\nAs for org.apache.hadoop.hive.thrift.TestHadoop20SAuthBridge.testSaslWithHiveMetaStore and \n\n{noformat}\njava.lang.NullPointerException: null\n\tat org.apache.hadoop.hive.metastore.HiveMetaStore.getDelegationToken(HiveMetaStore.java:5596)\n\tat org.apache.hadoop.hive.thrift.TestHadoop20SAuthBridge.getDelegationTokenStr(TestHadoop20SAuthBridge.java:318)\n\tat org.apache.hadoop.hive.thrift.TestHadoop20SAuthBridge.obtainTokenAndAddIntoUGI(TestHadoop20SAuthBridge.java:339)\n\tat org.apache.hadoop.hive.thrift.TestHadoop20SAuthBridge.testSaslWithHiveMetaStore(TestHadoop20SAuthBridge.java:231)\n{noformat}\n{noformat}\njava.lang.NullPointerException: null\n\tat org.apache.hadoop.hive.metastore.HiveMetaStore.getDelegationToken(HiveMetaStore.java:5596)\n\tat org.apache.hadoop.hive.thrift.TestHadoop20SAuthBridge.getDelegationTokenStr(TestHadoop20SAuthBridge.java:318)\n\tat org.apache.hadoop.hive.thrift.TestHadoop20SAuthBridge.access$100(TestHadoop20SAuthBridge.java:62)\n{noformat}\n\nBoth of these seem to be errors getting a delegation token, again something not connected with this connection retry issue.\n\nAs to the last one, org.apache.hive.hcatalog.streaming.TestStreaming.testEndpointConnection, that looks like an issue with derby setup? I'm not certain. It does look like a valid issue in and of itself, but again, not related to this patch.\n\n{noformat}\njava.sql.SQLException: Table/View 'TXNS' already exists in Schema 'APP'.\n\tat org.apache.derby.iapi.error.StandardException.newException(Unknown Source)\n\tat org.apache.derby.iapi.error.StandardException.newException(Unknown Source)\n\tat org.apache.derby.impl.sql.catalog.DataDictionaryImpl.duplicateDescriptorException(Unknown Source)\n\tat org.apache.derby.impl.sql.catalog.DataDictionaryImpl.addDescriptor(Unknown Source)\n\tat org.apache.derby.impl.sql.execute.CreateTableConstantAction.executeConstantAction(Unknown Source)\n\tat org.apache.derby.impl.sql.execute.MiscResultSet.open(Unknown Source)\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)\n\tat org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)\n\tat org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)\n\tat org.apache.hadoop.hive.metastore.txn.TxnDbUtil.prepDb(TxnDbUtil.java:72)\n\tat org.apache.hadoop.hive.metastore.txn.TxnDbUtil.prepDb(TxnDbUtil.java:131)\n\tat org.apache.hive.hcatalog.streaming.TestStreaming.<init>(TestStreaming.java:157)\n{noformat}\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-01-23T21:11:32.218+0000","updated":"2015-01-23T21:11:32.218+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12769109/comment/14292744","id":"14292744","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=thejas","name":"thejas","key":"thejas","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=thejas&avatarId=15902","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=thejas&avatarId=15902","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=thejas&avatarId=15902","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=thejas&avatarId=15902"},"displayName":"Thejas M Nair","active":true,"timeZone":"America/Los_Angeles"},"body":"+1\nI agree in context of metastore HA setup, it does makes sense to retry on JDOException as well.\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=thejas","name":"thejas","key":"thejas","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=thejas&avatarId=15902","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=thejas&avatarId=15902","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=thejas&avatarId=15902","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=thejas&avatarId=15902"},"displayName":"Thejas M Nair","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-01-27T00:46:24.308+0000","updated":"2015-01-27T00:46:24.308+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12769109/comment/14292835","id":"14292835","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"body":"Cancelling patch to resubmit an identical .3.patch so that the precommit tests don't skip it after the test issues we've had in the past couple of days.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-01-27T01:52:33.395+0000","updated":"2015-01-27T01:52:33.395+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12769109/comment/14292991","id":"14292991","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hiveqa","name":"hiveqa","key":"hiveqa","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=hiveqa&avatarId=17060","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hiveqa&avatarId=17060","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=hiveqa&avatarId=17060","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=hiveqa&avatarId=17060"},"displayName":"Hive QA","active":true,"timeZone":"America/Chicago"},"body":"\n\n{color:red}Overall{color}: -1 at least one tests failed\n\nHere are the results of testing the latest attachment:\nhttps://issues.apache.org/jira/secure/attachment/12694681/HIVE-9436.3.patch\n\n{color:red}ERROR:{color} -1 due to 3 failed/errored test(s), 7397 tests executed\n*Failed tests:*\n{noformat}\norg.apache.hadoop.hive.cli.TestCliDriver.testCliDriver_udaf_histogram_numeric\norg.apache.hadoop.hive.ql.TestMTQueries.testMTQueries1\norg.apache.hive.hcatalog.hbase.TestPigHBaseStorageHandler.org.apache.hive.hcatalog.hbase.TestPigHBaseStorageHandler\n{noformat}\n\nTest results: http://ec2-174-129-184-35.compute-1.amazonaws.com/jenkins/job/PreCommit-HIVE-TRUNK-Build/2528/testReport\nConsole output: http://ec2-174-129-184-35.compute-1.amazonaws.com/jenkins/job/PreCommit-HIVE-TRUNK-Build/2528/console\nTest logs: http://ec2-174-129-184-35.compute-1.amazonaws.com/logs/PreCommit-HIVE-TRUNK-Build-2528/\n\nMessages:\n{noformat}\nExecuting org.apache.hive.ptest.execution.PrepPhase\nExecuting org.apache.hive.ptest.execution.ExecutionPhase\nExecuting org.apache.hive.ptest.execution.ReportingPhase\nTests exited with: TestsFailedException: 3 tests failed\n{noformat}\n\nThis message is automatically generated.\n\nATTACHMENT ID: 12694681 - PreCommit-HIVE-TRUNK-Build","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hiveqa","name":"hiveqa","key":"hiveqa","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=hiveqa&avatarId=17060","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hiveqa&avatarId=17060","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=hiveqa&avatarId=17060","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=hiveqa&avatarId=17060"},"displayName":"Hive QA","active":true,"timeZone":"America/Chicago"},"created":"2015-01-27T05:17:15.983+0000","updated":"2015-01-27T05:17:15.983+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12769109/comment/14296096","id":"14296096","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"body":"The test failure now reported is down to 3, and they're unconnected to the issue being fixed here, so I will go ahead and commit this.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-01-28T23:57:18.408+0000","updated":"2015-01-28T23:57:18.408+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12769109/comment/14296099","id":"14296099","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"body":"Committed to trunk","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-01-28T23:58:49.014+0000","updated":"2015-01-28T23:58:49.014+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12769109/comment/14296104","id":"14296104","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"body":"[~vikram.dixit] - if you do respin an rc for 1.0, it would be useful to have this fix in as well - it's a simple fix which fixes retries from the client, and is a robustness fix. It isn't, however a breaking bug as I see it, since it is used only in the case of connection issues, where we give it a chance to retry instead of failing directly.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=sushanth","name":"sushanth","key":"sushanth","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=sushanth&avatarId=26812","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=sushanth&avatarId=26812","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=sushanth&avatarId=26812","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=sushanth&avatarId=26812"},"displayName":"Sushanth Sowmyan","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-01-29T00:02:37.999+0000","updated":"2015-01-29T00:02:37.999+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12769109/comment/14297959","id":"14297959","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=vikram.dixit","name":"vikram.dixit","key":"vikram.dixit","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Vikram Dixit K","active":true,"timeZone":"America/Los_Angeles"},"body":"Committed to RC for 1.0.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=vikram.dixit","name":"vikram.dixit","key":"vikram.dixit","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Vikram Dixit K","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-01-30T00:32:14.775+0000","updated":"2015-01-30T00:32:14.775+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12769109/comment/14327557","id":"14327557","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=thejas","name":"thejas","key":"thejas","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=thejas&avatarId=15902","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=thejas&avatarId=15902","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=thejas&avatarId=15902","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=thejas&avatarId=15902"},"displayName":"Thejas M Nair","active":true,"timeZone":"America/Los_Angeles"},"body":"Updating release version for jiras resolved in 1.0.0 .\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=thejas","name":"thejas","key":"thejas","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=thejas&avatarId=15902","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=thejas&avatarId=15902","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=thejas&avatarId=15902","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=thejas&avatarId=15902"},"displayName":"Thejas M Nair","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-02-19T14:45:00.165+0000","updated":"2015-02-19T14:45:00.165+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12769109/comment/14327853","id":"14327853","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=thejas","name":"thejas","key":"thejas","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=thejas&avatarId=15902","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=thejas&avatarId=15902","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=thejas&avatarId=15902","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=thejas&avatarId=15902"},"displayName":"Thejas M Nair","active":true,"timeZone":"America/Los_Angeles"},"body":"This issue has been fixed in Apache Hive 1.0.0. If there is any issue with the fix, please open a new jira to address it.\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=thejas","name":"thejas","key":"thejas","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=thejas&avatarId=15902","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=thejas&avatarId=15902","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=thejas&avatarId=15902","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=thejas&avatarId=15902"},"displayName":"Thejas M Nair","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-02-19T18:21:53.060+0000","updated":"2015-02-19T18:21:53.060+0000"}],"maxResults":21,"total":21,"startAt":0},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/HIVE-9436/votes","votes":0,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i24mwn:"}}