{"expand":"renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations","id":"12597945","self":"https://issues.apache.org/jira/rest/api/2/issue/12597945","key":"HADOOP-8577","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype","name":"Bug","subtask":false,"avatarId":21133},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/12310240","id":"12310240","key":"HADOOP","name":"Hadoop Common","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=12310240&avatarId=10095","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=12310240&avatarId=10095","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=12310240&avatarId=10095","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=12310240&avatarId=10095"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10292","id":"10292","description":"Scalable Distributed Computing","name":"Hadoop"}},"fixVersions":[],"aggregatetimespent":null,"resolution":{"self":"https://issues.apache.org/jira/rest/api/2/resolution/3","id":"3","description":"The problem is a duplicate of an existing issue.","name":"Duplicate"},"customfield_12312322":null,"customfield_12310220":"2012-07-08T16:27:08.969+0000","customfield_12312520":null,"customfield_12312323":null,"customfield_12312521":"Thu Jul 19 14:48:47 UTC 2012","customfield_12310420":"246792","customfield_12312320":null,"customfield_12310222":"1_*:*_1_*:*_1343053_*|*_5_*:*_2_*:*_944626502_*|*_4_*:*_1_*:*_11295","customfield_12312321":null,"resolutiondate":"2012-07-19T14:51:06.684+0000","workratio":0,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312923":null,"customfield_12312326":null,"customfield_12312920":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312921":null,"customfield_12312324":null,"customfield_12312720":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/HADOOP-8577/watchers","watchCount":5,"isWatching":false},"created":"2012-07-08T16:04:45.924+0000","customfield_12310192":null,"customfield_12310191":null,"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/4","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/minor.svg","name":"Minor","id":"4"},"labels":[],"customfield_12312333":null,"customfield_12310230":null,"customfield_12312334":null,"customfield_12313422":"false","customfield_12310310":"0.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":43200,"aggregatetimeoriginalestimate":43200,"customfield_12311120":null,"customfield_12312330":null,"versions":[],"issuelinks":[{"id":"12355294","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12355294","type":{"id":"12310000","name":"Duplicate","inward":"is duplicated by","outward":"duplicates","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/12310000"},"outwardIssue":{"id":"12554842","key":"HADOOP-8390","self":"https://issues.apache.org/jira/rest/api/2/issue/12554842","fields":{"summary":"TestFileSystemCanonicalization fails with JDK7","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are not closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Done"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.svg","name":"Major","id":"3"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype","name":"Bug","subtask":false,"avatarId":21133}}}}],"customfield_12312339":null,"assignee":null,"customfield_12312337":null,"customfield_12312338":null,"updated":"2012-07-19T14:51:06.768+0000","customfield_12312335":null,"customfield_12312336":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/5","description":"A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/resolved.png","name":"Resolved","id":"5","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Done"}},"components":[{"self":"https://issues.apache.org/jira/rest/api/2/component/12311440","id":"12311440","name":"test","description":"Testing support software"}],"timeoriginalestimate":43200,"description":"Hi,\n\nI have downloaded maven source code today itself and tried test it. I did following steps :\n1) mvn clean\n2) mvn compile\n3) mvn test\n\nAfter 3rd step one step failed. Stack trace of failed test is as follows :\n\nFailed tests:   testRealUserIPNotSpecified(org.apache.hadoop.security.TestDoAsEffectiveUser): The RPC must have failed proxyUser (auth:SIMPLE) via realUser1@HADOOP.APACHE.ORG (auth:SIMPLE)\n  testWithDirStringAndConf(org.apache.hadoop.fs.shell.TestPathData): checking exist\n  testPartialAuthority(org.apache.hadoop.fs.TestFileSystemCanonicalization): expected:<myfs://host.a.b:123> but was:<myfs://host.a:123>\n  testFullAuthority(org.apache.hadoop.fs.TestFileSystemCanonicalization): expected:<null> but was:<java.lang.IllegalArgumentException: Wrong FS: myfs://host/file, expected: myfs://host.a.b>\n  testShortAuthorityWithDefaultPort(org.apache.hadoop.fs.TestFileSystemCanonicalization): expected:<myfs://host.a.b:123> but was:<myfs://host:123>\n  testPartialAuthorityWithDefaultPort(org.apache.hadoop.fs.TestFileSystemCanonicalization): expected:<myfs://host.a.b:123> but was:<myfs://host.a:123>\n  testShortAuthority(org.apache.hadoop.fs.TestFileSystemCanonicalization): expected:<myfs://host.a.b:123> but was:<myfs://host:123>\n  testIpAuthorityWithOtherPort(org.apache.hadoop.fs.TestFileSystemCanonicalization): expected:<myfs://127.0.0.1:456> but was:<myfs://localhost:456>\n  testAuthorityFromDefaultFS(org.apache.hadoop.fs.TestFileSystemCanonicalization): expected:<myfs://host.a.b:123> but was:<myfs://host:123>\n  testFullAuthorityWithDefaultPort(org.apache.hadoop.fs.TestFileSystemCanonicalization): expected:<null> but was:<java.lang.IllegalArgumentException: Wrong FS: myfs://host/file, expected: myfs://host.a.b:123>\n  testShortAuthorityWithOtherPort(org.apache.hadoop.fs.TestFileSystemCanonicalization): expected:<myfs://host.a.b:456> but was:<myfs://host:456>\n  testPartialAuthorityWithOtherPort(org.apache.hadoop.fs.TestFileSystemCanonicalization): expected:<myfs://host.a.b:456> but was:<myfs://host.a:456>\n  testFullAuthorityWithOtherPort(org.apache.hadoop.fs.TestFileSystemCanonicalization): expected:<null> but was:<java.lang.IllegalArgumentException: Wrong FS: myfs://host:456/file, expected: myfs://host.a.b:456>\n  testIpAuthority(org.apache.hadoop.fs.TestFileSystemCanonicalization): expected:<myfs://127.0.0.1:123> but was:<myfs://localhost:123>\n  testIpAuthorityWithDefaultPort(org.apache.hadoop.fs.TestFileSystemCanonicalization): expected:<myfs://127.0.0.1:123> but was:<myfs://localhost:123>\n\nTests in error: \n  testUnqualifiedUriContents(org.apache.hadoop.fs.shell.TestPathData): `d1': No such file or directory\n\nI am newbie in Hadoop source code world. Please help me in building hadoop source code.","customfield_10010":null,"timetracking":{"originalEstimate":"12h","remainingEstimate":"12h","originalEstimateSeconds":43200,"remainingEstimateSeconds":43200},"customfield_12312026":null,"customfield_12312023":null,"customfield_12310320":null,"customfield_12312024":null,"customfield_12312340":null,"attachment":[],"aggregatetimeestimate":43200,"customfield_12312341":null,"customfield_12312220":null,"customfield_12312022":null,"customfield_12310921":null,"customfield_12310920":"43491","customfield_12312823":null,"summary":"The RPC must have failed proxyUser (auth:SIMPLE) via realUser1@HADOOP.APACHE.ORG (auth:SIMPLE)","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=shekhar.kotekar","name":"shekhar.kotekar","key":"shekhar.kotekar","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10443","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10443","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10443","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10443"},"displayName":"chandrashekhar Kotekar","active":true,"timeZone":"Asia/Kolkata"},"subtasks":[],"customfield_12310291":null,"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=shekhar.kotekar","name":"shekhar.kotekar","key":"shekhar.kotekar","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10443","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10443","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10443","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10443"},"displayName":"chandrashekhar Kotekar","active":true,"timeZone":"Asia/Kolkata"},"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":43200,"percent":0},"customfield_12311024":null,"environment":"Ubuntu 11\nJDK 1.7\nMaven 3.0.4","customfield_12313520":null,"customfield_12311020":null,"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":43200,"percent":0},"comment":{"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12597945/comment/13408957","id":"13408957","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=qwertymaniac","name":"qwertymaniac","key":"qwertymaniac","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=qwertymaniac&avatarId=16780","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=qwertymaniac&avatarId=16780","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=qwertymaniac&avatarId=16780","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=qwertymaniac&avatarId=16780"},"displayName":"Harsh J","active":true,"timeZone":"Asia/Kolkata"},"body":"The JIRA is to track issues with the project, not for user/dev-help. Please ask your question on common-dev[at]hadoop.apache.org mailing lists instead, and refrain from posting general questions on the JIRA. Thanks! :)\n\nP.s. The issue is your OS. Fix your /etc/hosts to use the right format of \"IP FQDN ALIAS\", instead of \"IP ALIAS FQDN\". In any case, please mail the right user/dev group. See http://hadoop.apache.org/mailing_lists.html","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=qwertymaniac","name":"qwertymaniac","key":"qwertymaniac","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=qwertymaniac&avatarId=16780","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=qwertymaniac&avatarId=16780","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=qwertymaniac&avatarId=16780","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=qwertymaniac&avatarId=16780"},"displayName":"Harsh J","active":true,"timeZone":"Asia/Kolkata"},"created":"2012-07-08T16:27:08.969+0000","updated":"2012-07-08T16:27:08.969+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12597945/comment/13418333","id":"13418333","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=daryn","name":"daryn","key":"daryn","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Daryn Sharp","active":true,"timeZone":"America/Chicago"},"body":"It's not his host config because this test is not using the system resolver.  The resolver for host-based tokens is overriding the call to the system resolver with one that simply returns lookups from a pre-defined map.\n\nThese failures should not be possible.  The only thing I can think of is that SecurityUtils is somehow broken and not using the resolver it's told to use.  I have no idea why this would be unique to JDK7...","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=daryn","name":"daryn","key":"daryn","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Daryn Sharp","active":true,"timeZone":"America/Chicago"},"created":"2012-07-19T14:48:47.531+0000","updated":"2012-07-19T14:48:47.531+0000"}],"maxResults":2,"total":2,"startAt":0},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/HADOOP-8577/votes","votes":0,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i07t5r:"}}